* Jan 04

** background

   both civil and common law.

   90% of all countries practice civil law. generally don't regard judges decisions as law. the idea of a civil code: could put all of the law a person would need to know in a code.

   henry II in england in 1100s. Wanted to create power over those pesky saxons. created a circuit of judges to ride around and judge. in rest of europe, tied to land (serfs). in england people didn't consider this. could buy and sell land. very different culture. henry's courts caught on and were popular. started developing more rights: habeas, etc. when they did have legislation it was to curtail the king, especially with the power of the purse.

   in europe, all this infighting after roman empire collapses. discovered a roman emperor's collection called Justinian's digest. in the 11th century rediscovered the digest and favored people who discovered it: the king is the law. in england, not so. Three sources of law: local, church, and justinian's digest. French revolution. french tired of corrupt courts: the 3 estates. wanted to level that and make an even playing field. got rid of all law, including the courts (hadn't kept records, and such, as in england). had been trying to put all the law in one place. napoleon in 1804 came up with project where the law was organized into one "easy to read" book. Napoleon owned Louisiana for 20 days (spain owned for 80 years).

   Thomas Jefferson wants to put in common law, but those pesky locals didn't want it. TJ sends Edward Livingston down from New York (in charge of federal bank starting up but run out on a subordinate's fraud scandal). He hired two lawyers to collect the law that is currently in place in LA. Added some spanish sources in addition to Napoleons. Accepted by US Senate in 1808. 1825 have to solve the problem that laws are in languages that no one speaks, english, spanish and french. rewrite in only english and french. 1870 code rewrite. contents are both french and US.

*** big difference LA and other civil

    we have adversarial procedures versus inquisitorial.

    in inquisitorial system, lawyers have no discovery power, no power to collect information. judges have all the power. often three judges for a trial. generally very little use of a jury (mostly criminal cases) and they are advised by the judge. we use common law procedures in a civil law system.

** articles 1-9

   what is law in louisiana

   sources of law in louisiana: legislation and custom

*** legislation

    legislation: is the solemn expression of legislative will

**** custom

     custom: practice repeated for a while that becomes the force of law

     there is no written rule that cases are authoritative law

     if you have a civil code article, you are expected to look up cases that interpret that article.

     in essence, we look quite like mississippi in common law.

**** fairness

     if no custom or legislation, you go with fairness.

**** retroactivity

     in the absence of explicit. substantive are prospective, procedural are retroactive and prospective.

     laws of substance: laws that affect your rights. us constitution prevents ex post facto.

**** public interest

     can't go against the public interest. used the word arrogate here.

** interpretation of laws 9--13

*** 9

    if a law is clear and unambiguous and applying doesn't lead to absurd, apply as written and don't allow any other interpretations.

*** 10

    if susceptible of different meanings, use the one

*** meaning of words

    familiar meaning or technical meaning if technical

*** ambiguous

    if ambiguous, look at the context of the article and the text of the law on the whole. and interpret with reference to each other.

    choice:
    1. purpose
    2. context
    3. same subject in connection with each other

** obligatiions

   start in 1756-1759

*** 1756

    obligation: legal relationship whereby a person (obligor) is bound to render a performance in favor of another (obligee). Performance consists of giving, doing, or not doing.

    obligation to give. under a contract to sell. once paid, you have an obligation to give the object for which was paid.

    obligation to: give, do, or not do.

*** 1757

**** source

     obligations arise from K and other declarations of will. (declaration of will: when you intentionally take on an obligation).

     obligations are legal duties, regardless of where the source came from.

**** management of the affairs of the other

     neighbor's window is broken and you call up a handyman to board up. neighbor will owe reimbursement costs.

** contract

*** 1906

    definition of K: promise or set of promise, the breach of which the law provides a remedy, performance is recognized as a duty.

    common law has which civil law does not:

    consideration: a bargained for excahange.
    cause: requires no exchange. i feel like doing this.

** harrison v gore

   minor sexually abused as child. brings action in K 8 years after for violating the promise of a good christian env at school was violated. statute of lim on K action is 10 years but in tort is 1 year. court finds the claim sounds in tort and is barred from relief. this sol is updated in 1993 to ten years after age of majority.

*** 3492

    defines prescription.

    delictual action. a tort.

* jan 22

** sources of obligations

   torts, negligence (delict, quasidelict)

   quasi contract

   contract

   negotiorum gestio: acting for another person.

   notice neighbor's window is broken, contract to have it
   fixed. neighbor will have to reimburse.

** K

   civil law: promsise or set of promises

   civil law: agreement by two or more parties where obligations are
   created, modified, or extinguished.

*** elemnts of K

    1. consent
    2. object
    3. capacity
    4. purpose

*** presumption

    capacity is presumed but rebuttable

*** 1920

    when lacking capacity, the other party can demand to confirm the
    contract.

**** hypo

     16 year old buys car

     rescission is effective upon agreement.

     a sale is perfected as soon as there is agreement on the price
     even though the thing is not delivered nor payment rendered.

*** unilateral v bilateral

    unilateral

    bilateral: exchange of promises

** consent

   offer and acceptance. 1927 consent.

   grumbling acceptance

* jan 24

** consent

   /clearly indicative of consent/: freedom from contract. you must
   obligate yourself. you must intend yourself to be bound.

** silence

*** section 69 restatement

    when an offerree failrs to respond to an offer silence operates as
    acceptanc ein following cases only:

    1. taken advantage of services knowing that payment was expected
    2. offeror specifies in the offer that assent may be manifested by silence
    3. previous dealings

*** 1942 Acceptance by silence

    When, because of /special circumstances/, the offeree's silence
    leads the offeror reasonably to believe that a contract has been
    formed, the offer is deemed accepted.

** irrevocable

   if revoked, have detrimental reliance benefits.

   if time specified or offeror manifested an intent to give time.

   all things are timed on receipt except acceptance of a revocable offer.

** duration

   saia: our first use of custom?

   #+BEGIN_QUOTE
   A more modern version of the above example might exist when a
   custom prevails in the building trade to the effect that a
   subcontractor's bid to a general contractor, te absence of a
   provision to the contrary, may be considered irrevocable after it
   has been used in preparation of the general contractor's bid to the
   owner, and has been accepted by the owner prior to the attempted
   revocation by the subcontractor.
   #+END_QUOTE

** options

   2620 eliminates consideration for option which had previously existed.

   ok so an option K gives different rights in remedy it
   seems. irrevocable gives right to detrimental reliance
   damages. whereas more equity is open in the option to the full
   expectation damages.

*** 1933 option contracts

    An option is a contract whereby /the parties agree/ that the offeror
    is bound by his offer for a specified period of time and that the
    offeree may accept within that time.

    made a big deal out of this agreement.

    read 2628 before youngblood. obligation v right.
* jan 29

** consent

   "clearly indicative of consent"

** rules about acceptance by performance

*** 1939-1941

    if an offer invites acceptance by performance AND the K is such
    that performance will be completed if commenced, then a K is
    formed when the offeree begins performance.

    if an offer can be accepted ONLY by completed performance, then
    the offer becomes irrevocable once the offeree has begun to
    perform and remains irrevocable for a reasonable time.

** silence  1942

   generally you hav eto have special circumstnaces. that's all that
   the code says so we look to the restatement because we are a mutt
   state.

   #+BEGIN_QUOTE
   When, because of special circumstances, the offeree's silence leads
   the offeror reasonably to believe that a contract has been formed,
   the offer is deemed accepted.
   #+END_QUOTE

   could be acceptance by silence if that's customary.

   international harvester: no acceptance by silence. the leasing
   company took a while but disputed it. rent was accepted for quite a
   while and court rejected this.

** offer

   manifestation of willingness to enter into a bargain so made as to
   justify another understanding

   section 24 of restatement. learn it.

*** three elements

    1) addressed to a person
    2) terms that are sufficient such that a court could enforce
    3) offeror intends to be bound if offeree just says yes

*** advertisement

    almost never an offer unless it invites acceptance by performance.

*** bids

    soliciting bids for public entities can be somewhere in the
    middle. may be an offer because there may be a duty to accept the
    lowest bid from a qualified bid.

    walker was not a public entity in that case

*** revocable offer

    can be revoked before acceptance. offeror is the master of the offer

*** irrevocable

    if has time or offeror manifests an intent to give some delay.

    36 days to accept class. burger king case where they had /at
    least/ 45 days to accept but accepted by performance at 46 days so
    that was reasonable. electrical subcontractor the bid was
    irrevocable for the length of time it takes to bid/contract etc.

** options and right of first refusal

*** right of first refusal

    giving the other party the first offer before extending to others.

    remedy is specific performance.

    when you decide to sell a thing, must offer to that person
    first. parties can stipulate a price.

*** option

    must set for the thing, price, formal requirements, and must
    include a time for the duration of the option.

*** 2627

    has 10/30 days to accept. if say nothing or turn it down free to
    sell it to someone else. if not sold in 6 months the person
    regains the right of first refusal. the right subsists.

*** 2628

    option or right of first refusal cannot extend beyond 10 years.

** acceptance

   compromise. 3071-3076. a settlement in common law is a compromise
   in civil law.


   "significant action taken to commence performance"

*** 1947

    #+BEGIN_QUOTE
    When, in the absence of a legal requirement, the parties have
    contemplated a certain form, it is presumed that they do not
    intend to be bound untl the contract is executed in that form.
    #+END_QUOTE

* jan 31

** option

   difficulty in louisiana. an option doesn't have to have
   consideration. need something that demonstrates the offeror's
   intent to be bound. an acceptance can suffice. shows some intent to
   be bound and some intent on the part of the offerree to /want/ that
   kind of power.

** compromise

   3072

   has to be in writing. where parties settle a dispute by making
   concessions.

** offer invites performance

   an offer can invite acceptance on its own terms. can invite
   acceptance by return promise. but can invite acceptance by return
   performance. the roofing cases fall into this case.

** stupid signatures

   if it doesn't fully comply with authentic act could be act under
   private signature duly acknowledged or act under private signature.

   any K in writing and signed is act under private signature.

** cause

   the reason why a person obligates himself.

   consideration is what separates "serious" problems from those
   quickly given and not meant. the bargained for exchange is what
   separates these. In civil law cause is the "reason" someone
   obligates himself. Reason not motive because it is meant to be
   knowable. Objective not subjective.

   cause can lead to binding of a gratuitous K as well. You promise
   the neighbor you would take care of his vette. its parked in your
   garage. as a depositary you need to take care of it as your
   own. suretyship: if you promise to pay the debts of another person

** donations

*** inter vivos

    1) gratuitous
       giving something to another person and getting nothing back.
    2) onerous
       demanding a service of some kind in return. something like a
       gift to it. its gifty.
    3) remunerative
       past consideration

*** gratuitous

    corporeal moveable: has a body. an object. incorporeal: no
    body. access. put you on a checking account.

    gratuitous donation of corporeal moveable: actual delivery with
    donative intent. article 1543
    #+BEGIN_QUOTE
    the donation inter vivos of a corporeal moveable may also be made
    by delivery of the thing to the donee without any other formality.
    #+END_QUOTE

    lease for mineral rights. incorporeal immoveable.

    article 1541
    #+BEGIN_QUOTE
    article 1541: form required for donations
    A donation inter vivos shall be made by authentic act under the
    penalty of absolute nullity, unless otherwise expressly permitted
    by law.
    #+END_QUOTE

    otherwise absolutely null

    Gratuitous Donations:
    1) If corporeal or incorporeal immovable, MUT be i nauthentic act
       form or else absolutely null (art 1541). Act must identity
       donor, donee, and describe thing. Ex: /Spanier v. De Voi/
    2) If corporeal movable, may be manual gift plus donative intent
       art 1543
    3) If incorporeal movable, then follow UCC Title 9 (outside of
       scope of this class).

*** remunerative and onerous donations

    getting something back.

    1526 & 1527

    drew an arbitrary line in the sand. if what you are getting is
    worth less than 2/3 it's gratuitous and then you need an authentic
    act. if its "susceptible of being measured of money".

    many times where someone might take care of someone. usually don't
    measure things too well.

* feb 5

** dorgenoy v droz

   valid as a gratuitous donation

** hypothets

*** corporeal moveable

** absence of cause

   if no cause, absence of cause and the obligation is absolutely null

** failure of cause is different

   absence no cause in beginning. failure of cause is where cause fails after the initial part.

*** losecco

    wants to buy oranges. gregory is a farmer. agree that for 8k
    losecco

    assumed risk "usual, known, or foreseen"

** unlawful cause

   a type of absence of cause.

   gambling debts: know or not know about the reason for a loan

* feb 7

** losecco

   aleatory contract.

** unlawful cause

   if cause or object is unlawful or agains public policy, then the K is /ABSOLUTELY/ null.

** public policy

   the investigator who would only bill if he found evidence of husband cheating. the cause

** gambling

   hazy distinction between cause and object.

   she wants us to make a distinction of legal and illegal
   gambling. the law review article makes good distinction between
   legal and illegal gambling.

** unclean hands

   common law doctrine that has been adopted in louisiana. if you've
   done something dirty and want the court to enforce something the
   court will leave you where it found you.

   simulation can be absolute or relative: parties declare that K
   means one thing but they actually mean something else. if they say
   its a "sale" but it has no effect its an absolute
   simulation. relative: intend an effect just one different from the
   one they say. here call it a sale but its actually an onerous
   donation. some simulations are legal, some are illegal. bona fide
   purchaser doctrine. sale to the 3rd party is clean.

   the rule. if a single party they can have their day in
   court. dissent is better in this case.

** detrimental reliance

*** elements

    1) promise - of a special kind likely to induce reliance
    2) promisor knew or should have known of #1
    3) other party's reliance is reasonable & led to a detriment
    4) then MAY be enfroced to extent necessary


*** comparison

    its the same. last line. it is a losing argument. very
    rare. winning is also very rare.

** natural obligations

   1760 obligations in general. we are not in contract land anymore.

   natural obligation is where the law implies a particular moral
   duty.

   1761 that moral duty is NOT ENFORCEABLE.

   1762 different types of moral obligations

   - extinguished debts in bankruptcy or prescription
   - obligation incurred by a person without capacity but with
     *discernment*
   - an executor who is not bound by law to follow the wishes of the
     decedant but should. think a failure of form.


*** autofinance case

    gonna keep paying loan after bankruptcy. moral obligation. quits
    paying. cannot get his money back.

* feb 14

** roadmap

*** obligations

**** obligations in general
     - definition
     - effects

**** natural obligations

**** 3 kinds of obligations

**** 4 transfer

****  5 proof

     - person who claims there is an obligation has to prove it
     - private signature, authentic act, duly acknowledged,
     - over under $500. corroborating witness

**** 6 extinction

*** contracts

**** definition

     - kinds
     - definiiton

**** capacity

**** consent

**** vices of consent

**** cause

** review

*** detrimental reliance

**** is promissory estroppel

     1. A promsie such that the promisor knew or should have known
        would induce other party's reliance to his detriment
     2. other parties relies on promise reasonably and t ohis detriment
     3. no other remedy
     4. recovery MAY be limited to expenses, damages
     5. Reliance on a gratuitous promise made without required
        formalities is NOT reasonable

*** natural obligations

    when the law implies a moral duty. it is NOT enforceable at
    law. the code gives 3 examples in a non-exclusive list.

**** examples

     1. a debt that has proscribes
     2. an obligation entered into someone who lacks capacity but has discernment
     3. an obligation listed in an invalid will

**** take back

     if freely given in connection with a natural obligation cannot
     take it back.

**** elevation to a contract

     can serve as the cause of a contract

***** required

      1. duty to a particular person
      2. strong conscience
      3. can be fulfilled with money
      4. clear and distinct and unequivocal statement of intent to
         perform the obligation
      5. not against public policy

*** assent

    conduct under the circumstances that clearly manifests assent

** remission


*** act that leads to a presumption

    if creditor voluntarily surrenders the instrument. presumption of
    an intent to remit.

*** three grounds to undo

    1. due to a condition not fulfilled
    2. obtained out of fraud, duress, or undue influence
    3. ingratitude

** compromise

   written agreement between parties in order to settle
   disputes. common law allows for an issue or potential issue or
   uncertainty. doesn't have to be a filed action. in WRITING

   parties have to have capacity. compromise has to be lawful.

   once a compromise you cannot sue on those basis. precludes
   subsequent actions on those matters. can be rescinder for error or
   fraud but not error of law.
