* Capacity

** four required elements

   1. capacity
   2. cause
   3. consent
   4. object

   /par excellence/: better or more than all others of the same kind

   generally defined as the ability to exercise certain rights and duties.

** Julius Cohen Jeweler, Inc. v. Succession of Jumonville

*** facts

    Senator Jumonville was known to a jeweller as a large spender. In
    May of 1982 his family seeks to have him declared interdicted and
    to have provisional curators appointed to manage affairs. The trial
    court so appointed the curators /without/ a hearing declaring the
    Senator interdicted.

    In Feburary of 1983, the jeweler meets with the Senator who
    purchases $190,000 of jewelery for family memebers. His daughter
    happens to meet the jeweler and returns some so that the result is
    only $40,000 of jewelery purchased. It was not until the next day
    that the jewler heard of the pending interdiction suit. Cohen twice
    tried to persuade the Senator to cancel the jewelry sale.

    The Senator died in May of 1983 about a year after the intial
    interdiction proceeding. The jeweler brought action against the
    succession for the unpaid balance of $40,000.

*** lower court

    Petitioner plaintiff argued that the Senator had entered into a
    binding contract. Further, the petitioner-plaintiff argued that
    defendants were equitably estopped "from asserting the defense of
    incapcity to contract".

    Defendants argued that the contract was null because of the
    filing for interdiction and appointment of the provisional
    curators voided any attempt by the Senator to contract after
    that date. They had only to ask for a rescission. They also
    claimed that failure to recoup the remaining balance of jewelry
    was a failure to mitigate his damages.

*** rule

    "The general rule is that all persons are presumed cappable of
    contracting, except those who have been declared incapable by law".

    1919: Right to plead rescission
    #+BEGIN_QUOTE
    A contract made by a person without legal capacity is relatively
    null and may be rescinded only at the request of that person or his
    legal reprsentative.

    Comment: (d) Under this article, a contract made by an interdict
    after the date of /successfull/ application for interdiction is
    relatively null.
    #+END_QUOTE

    1926: Attack on noninterdicted decedent's contracts
    #+BEGIN_QUOTE
    A contract made by a noninterdicted person deprived of reason at
    the time of contracting may be attacked after his death, on the
    ground of incapacity, only when the contract is gratuitous, or it
    evidences lack of understanding, or was made within thirty days
    of his death, or when application for /interdiction was filed
    before his death./
    #+END_QUOTE

    "The conclusive presumption to contract arises only after a
    judgment of interdiction" Cited as 1788.1 but this seems to be
    "Joint obligations for obligors or obligees"

    1925: Noninterdicted person deprived of reason; protection of
    innocent contracting party by onerous title
    #+BEGIN_QUOTE
    A noninterdicted person, who was /deprived of reason at the time/
    of contracting, may obtain rescission of an onerous contract upon
    the ground of incapcacity only upon /showing that the other party
    knew or should have known that person's incapacity./
    #+END_QUOTE

*** holding

    The rescission effort by the defense fails for failure to
    demonstrate the two required showings: incapacity and known or
    should have known. The lack of a hearing determining interdiction
    prevents the court from assuming this quite harsh curbing of civil
    rights.

*** reasoning

    The succession can attack the contract under the "interdiction was
    filed before his death" allowance of 1926. However, their claim
    that the Senator lacked capacity fails because a court never ruled
    him interdicted. The appellate court holds that the lower court was
    incorrect in finding the appointed curators sufficient to presume
    the Senator interdicted.

    As such, the defendants can only argue that the senator was
    incapable at the time and the jeweler knew or should have
    known. The testimony of a doctor is excluded as hearsay and the
    court points out that the Senator hosted the jeweler along with
    several others at a fancy dinner party, along with paying for
    lodging and accomodations as in the past. "It was undisputed that
    the Senator was unaware of the interdiction proceedings ... until
    ... two days after the sale."

*** takeaway

** Rabin v Blazas

*** facts

    Blazas is an 80 year old man who contracted to purchase two
    properties. At the time of inspecting the properties, although
    he had difficulty hearing plaintiff he did not have issues
    understanding him. He drove plaintiff to the property and had a
    discussion about interest rates, financing, and the advantage of
    paying cash. The contract was for $55,000 with a 10% down
    payment in 48 hours. This period elapsed without payment and a
    suit results for breach.

    A doctor testified at the trial court that Blazas (D) had a
    brain condition that would render him incapable. This diagnosis
    was made six months after the contract in question. The doctor
    could not say if the symptoms were present at the time of
    contracting.

*** lower court

    Blazas, defendant, argues that due to his age and infirmity, he
    was incapable of contracting and the contract should be
    rescinded. The court rejects this argument and rules for
    plaintiff in amount of $12,450.

*** rule

    1925: Noninterdicted person deprived of reason; protection of
    innocent contracting party by onerous title
    #+BEGIN_QUOTE
    A noninterdicted person, who was /deprived of reason at the time/
    of contracting, may obtain rescission of an onerous contract upon
    the ground of incapcacity only upon /showing that the other party
    knew or should have known that person's incapacity./
    #+END_QUOTE

*** holding

    The doctor fails to demonstrate that he was incapable at the
    time of contracting. As such the contract is valid and damages
    are owed. The lower court is affirmed.

*** reasoning

    In order to rescind the contract, the doctor must satisfy both
    elements of 1925: (1) that his was incapable at the time of
    contracting and (2) that the other party knew or should have
    known. The court stops the analysis at the failure to
    demonstrate (1). The doctor could not state that the onset of
    the disease was present at the time of contracting, and
    therefore the defendant had failed to prove his case to
    rescind. But the court continues and notes that testimony
    appears to show a lucid and savvy property owner engaged in
    technical discussions. /If/ he was incapacitated, the other
    party would have had no idea.

*** takeaway

* Consent

** Union of the Parties' Will

*** Belgard v Collins

**** facts

     Mrs. Collins' store was damaged in a storm. Mr. Belgard runs an
     engineering consulting firm whose business plan is to provide
     bids based on their own engineering inspection and recoup 25% of
     amount supplied by the insurance company above the original
     payout.

     Mr. Belgard claims that he offered to bring his engineer to go
     over the details. He did so while present and compiled the
     engineers report with his bid and two others. Mrs. Collins asked
     him to submit this package to the insurnace which he claims is
     her acceptance of the services.

     Mrs. Collins states that she thought that Mr. Belgard was a
     contractor looking to bid on the repair work. Mrs. Collins
     understood that she was hiring the engineer and not
     Mr. Belgard. She had a conversation about rates with Mr. Beard,
     which he confirmed. Mr. Beard stated he had no knowledge of any
     agreement between Mrs. Collins and Mr. Belgard.

     Mrs. Collins received an advance from the insurance company of
     $50,000 and sought to pay Mr. Beard for his services. He said
     that he had been paid by Mr. Belgard. Mrs. Collins tried to
     determine why the consultant had paid the engineer and was not
     told how much. Mrs. Collins claimed that Mr. Belgard submitted
     the package of information of his own accord.

     All three bids were rejected and Mrs. Collins received $123,000
     from the insurance. Mr. Belgard brings suit for 25% of the
     payout above the $50,000 initial check.

**** lower court

     Found in favor of Mrs. Collins stating that there was never a
     "meeting of the minds" and thus no oral contract.

**** rule

     Four elements for a valid contract:
     1. the parties must have legal capacity to contract;
     2. the parties' mutual consent must be freely given;
     3. there must be a lawful cause or purpose; and
     4. the object of the contract must be lawful, possible, and
        determined or determinable.

**** holding

     The lower court is affirmed and there was no oral contract
     between the parties.

     However, Mrs. Collins received the economic benefit of the
     engineer's services and the lower court's order is amended for
     her to pay the $1300 fee.

**** reasoning

     The lower court found that there was no "meeting of the minds"
     of the two parties--a finding of fact. As such, appellate review
     to disturb this finding is only in the case the conclusion is
     "clearly wrong".

     The court notes that Mrs. Collins believed Mr. Belgard was a
     contractor. She tried to pay the engineer, a step that would not
     be necessary if she thought she was dealing with a
     contractor. This step was months after Mr. Belgard thinks she
     agreed to the consulting contract.

     There is no evidence to suggest a failing of a contract for lack
     of "meeting of the minds" is "clearly wrong" and the lower court
     is affirmed.

**** takeaway

** Expressing Consent

*** North Louisiana Milk Producers Assoc, Inc. v. Southland Corporation

**** facts

     A dispute between milk producer and consumer. The two had dealt
     for years together, taking the higher of the minimum price set
     by a state and federal agency. After time, this price was
     determined to be too low by the seller (North Louisiana Milk
     Producers Association).

     "Effective for the month of ____, all milk purchased by your
     plant will be priced at $_____. Your acceptance of milk from
     members of this assoc during .. will constitute your agreement
     to these announced prices."

     Consumer of milk (defendant) disputes these prices with several
     letters over the months. Plaintiff responds that they reject the
     counter offer and state that all milk received from members are
     on terms previously stated. Defendant continued to order milk in
     customary way: supervisors ordering by phone with no discussion
     of price at time.

     Plaintiff billed at described prices, defendant paid at the
     customary higher of the two minimum prices set by the agencies,
     leading to a balance of $79,958 at the time of suit. (why not in
     federal court then?).

**** lower court

     Rules for plaintiff at his price. "defendant contends on appeal
     that since there was no agreement or contract as to price, the
     lower court erred in supplying the price".

**** rule

     #+BEGIN_QUOTE
     To be considered properly as such, the offer must fulfill the
     following three requirements clearly established in the
     Louisiana Civil Code:
     1) The design to give the other party the right of concluding
        the contract by his assent
     2) The offeror's intention to obligate himself
     3) A Serious intent
     #+END_QUOTE

**** holding

     Plaintiff made an operative offer that specified the mode of
     acceptance: ordering milk.

     Defendant never crafted a true counter offer as it did not
     specify a specific quantity of milk at a specific price.

     Therefore when defendant's employees ordered milk from plaintiff
     without conditioning as to price, it served as acceptance of
     standing offer to sell at stated price by plaintiff.

**** reasoning

     Before 1976, the time when the producer divereged from the
     prices set by the agencies, each side could rightfully be
     considered an offeror. An offer to sell at price X or an offer
     to purchase at price X. Plaintiffs broke with this custom in
     1976 and set stated prices. "[I]t made a standing or operative
     offer to sell for the stated period as was expressed in the
     monthly correspondence as well as in some telephone calls
     between the managesr". The method of acceptance was
     explicit--ordering milk--and "not the a promise by defendant
     that it would order in the future".

     Plaintiff clearly would not acquiesce to the offer of defendant
     so it is an offer to sell, not an offer to purchase
     after 1976. Defendant could have phrased its orders "sell us X
     amount of milk at Y dollars" yet did not do so. Thus there was
     never a true offer of the supposed "counter offer".

**** takeaway

*** Illinois Central Gulf Railroad Company v. International Harvester Company

**** facts

     A company rents property on Poydras street. When the superdome
     is constructed, the property value increases. The company asks
     to sublease to a parking garage structure, to which the leasing
     company declines. The company does so anyways, sending rent
     payments for the next two and a half years. Sues for eviction in
     Novemeber 1977 when sublease was started in January 1975.

**** lower court

     Trial court ruled that there was no consent to a lease
     modification and therefore the actions were a breach of the
     lease. The contract included a right to terminate which they
     were validly exercising.

     The appellate court overturned this, ruling "by its silence and
     inaction, had impliedly assented to the sublease and altered
     used of the premises"

**** rule

     "According to the civil code, consent may be implied in the
     following instances:

     #+BEGIN_QUOTE
     ... when it is manifested by actions, even by silence or by
     inaction, in cases win which they can from the circumstances be
     supposed to mean, or by legal presumption are directed to be
     considered as evidence of assent.

     when (actions without words) are done under circumstances that
     naturally imply a consent to such contract... [1927]
     #+END_QUOTE

     i don't find the above in 1927 at all:

     1927: Consent
     #+BEGIN_QUOTE
     A contract is formed by the consent of the parties established
     through offer and acceptance.

     Unless the law prescribes a certain formality for the intended
     contract, offer and acceptance m,ay be made orally, in writing,
     or by action or inaction that /under the circumstances is clearly
     indicative of consent./

     Unless otherwise specified in the offer, there need not be
     conformity between the manner in which the offer is made and the
     manner in which the acceptance is made.
     #+END_QUOTE

**** holding

     The landlord had not demonstrated consent to the lease modification

**** reasoning

     There is no legal presumption of acceptance form the accepting
     of rent. So the question is "whether the judge exercised sound
     discretion in determing that Illinois Central's consent to a
     modification of the lease contract was not unequivocally implied
     from its silence and inaction under the particular circumstances
     of the instant case."

     Lack of finding of consent. The delay is not inconsistent with
     this. Note the size of the company, amount of holdings, new
     management, etc. The lawsuit was filed soon after they found out
     the circumstances.

**** takeaway

*** Marine Ins Co Limited of London, Eng. v. Rehm

**** facts

     A man's car was stolen out of a parking garage. His insurance is
     suing the parking lot company.

**** lower court

     seems to have agreed with defendants that the parking recepit
     declaimed all liability

**** rule

**** holding

     there was liability. there was no consent to the language on the receipt.

**** reasoning

     "the check given by the defendant in this case to Klein upon the
     receipt of his automobile wa nothing more than a means of
     identifying his property or a mere receipt and was not a special
     contract".

**** takeaway

** Cashio v. Amco Transmissions

*** facts

    A man leaves his car with a transmission shop with $3.00 parking
    for a saints game. he is aware that the lot will be unattended
    as both the attendant and the owner are attending the game as
    well. The car is stolen and he brings this suit.

*** lower court

*** rule

    #+BEGIN_QUOTE
    ... when it is manifested by actions, even by silence or by
    inaction, in cases win which they can from the circumstances be
    supposed to mean, or by legal presumption are directed to be
    considered as evidence of assent.

    when (actions without words) are done under circumstances that
    naturally imply a consent to such contract... [1927]
    #+END_QUOTE

    same reasoning as above but here we legal presumption

*** holding

    there was no evidence of consent to the contrary so defendants
    consented as depositaries rather than lessors.

*** reasoning

    Louisiana law has taken up this very issue. R.S. 9:2783 provides
    a safe harbor to prevent a contract of deposit and but only one
    of hiring or letting out space. Compliance with this is not the
    only way to create a lease agreemtn. In a related case, the
    parking lot owner did not comply with the law but the court
    found that there was a lease and not deposit contract by "the
    mutual intent of the parties can be inferred from the
    circumstances".

    While the parking lot was clearly going to be unat;wtended, the
    customer retained exclusive rights to the vehicle at all times,
    had unrestricted access to the lot, the court finds that there
    was a depository relationship created. The sign did not clearly
    declaim liability and thus a depository relationship was created

*** takeaway

** The Offer

*** Johnson v. Capital City Ford Company, Inc.

**** notes

     #+BEGIN_QUOTE
     Plaintiff's /motive/ in purchasing ... was not only to receive it
     for the trade-in and boot given, but also to receive the right ...
     #+END_QUOTE

     goes to cause. Tate was a luminary and uses this cause hook to
     make it an offer.

**** facts

     A newspaper ran an advertisement offering (?) to trade 1955 ford
     pickups for 1954 pickups purchased in the next two weeks. A man
     went in an purchased one and then later was denied the trade for
     a 1955 Ford pickup.

     The contract to purchase stipulated that it "compirse[d] the
     entire agreement pertaining to this purhcase and no other
     agreement of any kind, verbal understanding or promise
     whatsoever, will be recognized".

**** lower court

**** rule

     "defendant was under a duty to notify plaintiff of any
     modification of the newspaper offer. the omission in this
     contract is construed against defendant."

**** holding

     The court holds that the original contract for sale was the mode
     of acceptance of the advertisement's offer to trade a 54 for
     a 55. This was a separate agreement from the original sale and
     therefore the full integration clause does not exclude parole
     evidence of the other contract. The dissent takes issue with a
     newspaper ad being a true offer rather than an invitation to
     offer, the majority seems to hold that its ambiguous so that
     ambiguity is held against the author. seems a little harsh.

**** reasoning

     As to whether it was an offer, the court seems to say if it was
     ambiguous then that ambiguity is held against the
     author. Defendant argued that plaintiff was under a duty to
     state that he was accepting the offer. Court points out that in
     fact they were under a duty to talk about any modifications that
     to the offer. Defendants were arguing that if he was accepting
     the deal they would have offered less on trade in value.

     Discussion of whether the newspaper article was part of the
     signed contract. court finds that no it is not. it is
     separate. the sales contract is the acceptance of the newspaper
     offer, "creating another and a separate obligation".

**** takeaway

*** North Central Utilities, Inc. v. Walker Community Water System, Inc.

**** facts

     Walker Community Water System advertised for bids, for which
     North Central Utilities was the lowest bidder. Defendant did not
     accept this bid and Plaintiff brings action to force acceptance
     of bid.

**** lower court

     Held in favor of defendant but seems to be on grounds relating
     to public utility and responsibilities consequent.

**** rule

     annoyingly, does not cite the civil code. goes to common law in
     another state and then states that the louisiana law "is
     basically the same". how about a cite and how it differs then.

     here's the paraphrase of common law that is "basically the same"
     as our law but not a quote of our law, just random shiz.

     "For any proposal to qualify as an offer, it  must reflect the
     intent of the author to give to the other party the right to
     concluding the contract by assent". This is so foundational to
     contracts that it is so strange that there isn't some language
     in 192x stating exactly that.

**** holding

     The language was not an offer and therefore ofcourse the utility
     was free to reject any and all bids it so desired.

**** reasoning

     Ignores public utility laws and looks at the request for
     bids. Finds that this was not an offer but "merely indicates an
     intent to sell, and does not constitute an offer to accept the
     highest bid".

**** takeaway

** Duration of the Offer

*** Schulingkamp v. Aicklen

**** facts

     Defendant send irrecovable offer to Plaintiff on November 15. On
     December 21, sends revocation of offer. On December 26,
     Plaintiff signs acceptance and sends on January 2.

     Offer states was irrevocable through act of sale which plaintiff
     argues means the defendants were unable to revoke.

**** lower court

**** rule

     1928
     #+BEGIN_QUOTE
     An offer that specifies a period of time for acceptance is
     irrevocable during that time.

     When the offeror manifests an intent to give the offeree a delay
     within which to accept, without specifying a time, the offer is
     irrevocable for /a reasonable time/.
     #+END_QUOTE

**** holding

     The irrevocable offer was open for a reasonable amount of time
     and then revoked. There was no contract since there was no consent.

**** reasoning

     With no time specified, the standard from 1928 is a "reasonable
     time". This is circumstance specific and the court decides that
     a reasonble period of time has passed in which the plaintiff
     could have accepted. The factors used are elided in this
     presentation for some dumb reason so we don't get to see why the
     court thinks that 36 days was an unreasonable amount of time.

**** takeaway

*** Meyers v. Burger King Corporation

**** notes

     meyers works for parkway. parkway offers to rebuild burger
     king. he sues deep pockets. BK says they have a K and the K will
     indemnify BK from any lawsuits from injury. but BK has no power
     to affect the workplace safety.

**** facts

     Injury relating to construction in a Burger King. Relevant to us
     is whether there was a contract between Parkway (Burger King's
     insurer). Parkway states that it does not have a contract with
     BK since their offer stated the price was in effect for at least
     45 days. Burger King did not accept within 45 days so Parkway
     argues the offer had expired leaving a formation issue.

**** lower court

**** rule

     1928
     #+BEGIN_QUOTE
     An offer that specifies a period of time for acceptance is
     irrevocable during that time.

     When the offeror manifests an intent to give the offeree a delay
     within which to accept, without specifying a time, the offer is
     irrevocable for /a reasonable time/.
     #+END_QUOTE

     1927
     #+BEGIN_QUOTE
     ...
     Unless otherwise specified in the offer, there need not be
     conformity between the manner in which the offer is made and the
     manner in which the acceptance is made.
     #+END_QUOTE

**** holding

     There was a valid acceptance of the contract while the offer was
     still open. The offer was subject to a reasonable time duration
     as per 1928 and that reasonable time had not expired.

**** reasoning

     The offer did not expire at 45 days, it was open at least 45
     days. Since no time was actually specified but some time was
     indicated, 1928 stipulates that the offer is open for a
     reasonable time. The court doesn't have to investigate this as
     they find Burger King tacitly accepted the offer at 46 days when
     it invited Parkway to begin renovations. The court doesn't need
     intricate analysis that 46 days is a reasonable time with a
     minimum floor of 45 days.

**** takeaway

*** W. M. Heroman & Co., Inc. v. Saia Electric, Inc.

**** facts

     Saia Electric furnished a bid for electrical work. The
     negotiations for the contract took a further 3 months during
     which Saia was contacted a few times so that they knew the
     progress was proceeding. At construction time, Saia would not
     honor the bid price and furnished a price 100K
     larger. Contractor got another sub for a cost plus job and
     brings suit for the difference in price, 95K.

**** lower court

**** rule

     1928
     #+BEGIN_QUOTE
     An offer that specifies a period of time for acceptance is
     irrevocable during that time.

     When the offeror manifests an intent to give the offeree a delay
     within which to acccept, without specifying a time, the offer is
     irrevocable for a reasonable time.
     #+END_QUOTE

**** holding

     1928 governs the bid of the subcontractor. It was irrevocable
     and was revoked. Plaintiff recovers the difference paid versus
     the bid price, minus a reasonable amount that was not
     anticipated in either bid.

**** reasoning

     The court points to recent decisions that confirm that bids are
     irrevocable offers. then find that the three months that have
     elapsed was not an unreasonable time for a construction project
     and note that Saia had been contacted during this time and knew
     that the contract was progressing.

**** takeaway

** Option Contracts and rights of first refusal

*** Glover v. Abney

**** facts

     An action after death lseeking specific performance to convey
     land promised to Glover. Abney had signed a promise to sell land
     to Glover and then died.

**** lower court

     Ruled that the promise lacked consideration and was therefore
     unenforceable. This is in 1926 and the requirement for
     consideration has since been removed.

**** rule

     At the time, option contracts required some consideration.

**** holding

     This promise lacked consideration and therefore the heirs were
     not bound by it.

**** reasoning

**** takeaway

*** Youngblood v Rosedale Develop. Co., L.L.C.

**** facts

     Plaintiff owns 363 acres of land and Defendant is developing it
     in stages. Originally purchased 15 acres which comes with an
     option:

     #+BEGIN_QUOTE
     Such a partial exercise or any subsequent partial exercise shall
     have the effect of extending this option for an additional three
     year period from the closing date of the property upon which the
     option has last been exercised.
     #+END_QUOTE

     Over 6 years, Rosedale exrcises option four times for about 56
     acres. Defendant gives notice of intent to exercise option again
     and Plaintiffs sue to have option declared null.

**** lower court

     Rules that the contract fits into the exception for contracts
     that give rise to obligations of continuous or periodic performance.

**** rule

     #+BEGIN_QUOTE
     Art 2628: Time limitation for option and right of first refusal

     An option or a right of first refusal that concerns an immovable
     thing may not be granted for a term longer than ten yeras. If a
     longer time for an option or a right of first refusal has been
     stipulated in a contract, that time shall be reduced to ten
     years. Nevertheless, if the option or right of first refusal is
     granted in connection with a contract that gives rise to
     obligations of continuous or periodic performance, an option or a
     right of first refusal may be granted for as long a period as
     required for the performance of those obligations.
     #+END_QUOTE

**** holding

     The contract deserves no such exception, and is therefore limited
     to the ten year maximum as provided in 2628. The associated
     contract has no obligations that are recurring

**** reasoning

     #+BEGIN_QUOTE
     Never did the original purchases of the first 15 acres of land,
     nor the defendant when it purchased land by means of the option
     to buy, obligate themselves to the development of the whole or
     any part of the 363 acres of land. There is no agreement or
     contract to the ultimate development by increments, nor any
     requirement of the defendant to purchase any addditional
     acreages. Since the contract to buy was not granted "in
     connection with a contract that gives rise to obligations of
     continuous or periodic performance," then it cannot fall into the
     exception stipulated in Louisiana Civil Code article 2628.
     #+END_QUOTE

     Since there is no exception to allow the option to keep renewing
     forever, it must be capped at ten years which the lower court did
     not do.

**** takeaway


** Communication of the Acceptance and the Time of Contract Formation

*** Ryder v. Frost

**** facts

     Ryder and Frost were business partners in a failed enterprise
     with a debt of $6,000 owed. Ryder had indemnified Frost of all
     debts and was solely responsible for the debt. The holder of the
     debt offered to settle the debt for $2000. Ryder wrote to Frost
     that they should each pay the $1000. Frost responded that he had
     no obligations whatsoever and that he was quite happy in his
     station. However, he would happily $500 to clear the debt from
     court papers. Ryder proceeded to settle the debt for $2000 and
     then seeks to get $500 from Frost.

     From the opinion, it appears that Ryder may not have told Frost
     that he accepted his proposition for some time.

**** lower court

     Is reversed but not clear on what grounds they ruled.

**** rule

     Implied consent may be manifested by actions.

**** holding

     There was a contract between the two. Ryder accepted and
     performed.

     Two questions as the court sees it:
     1) was there an assent by Ryder to Frosts prposition, within a
        reasonable time?
     2) Was it indespensable that earlier notice of acceptance should
        have been given?

**** reasoning

     1) Clearly there was an assent. Ryder satisfying the debt was the
        object of Frost and it was accomplished. It is not necessary
        for the offeror to know of acceptance.

        The court reasons that an offer accepted before death of the
        person making the offer is valid even if that person dies
        before knowing it has been accepted. If death won't extinguish
        obligations, then this one is valid.

     2) This one isn't answered so clearly. The court finds no injury
        to the enjoyment of the fruits of agreement and therefore find
        no fault. The agreement did not specify a time within which
        Frost had to be made aware.

*** Cardinal Wholesale Supply, Inc. v. Chaisson

**** facts

     Two co-owners of a defendant business sign personal guarantees
     when applying for credit from plaintiff. The guarantee contained
     a waiver of written acceptance. The credit application was denied
     and Cardinal placed the forms into a safety deposit box. Two
     years later the two cosigners had sold their stake. Four years
     later defendant company opens a line of credit and goes
     insolvent. At this point (eight years after they were originally
     signed) Cardinal pulls the personal guarantees out of the safety
     deposit box, signs them, and sues the two men for the debts of
     the company.

**** lower court

**** rule

**** holding

     The plaintiff did not accept the guarantees as they were given
     in 1972. The two men certainly did not mean to bind themselves to
     the debts of this company 8 years later.

**** reasoning

     The waiver of /notice/ of acceptance does not waive the
     requirement of acceptance. The guarantees were given to induce a
     line of credit. Cardinal did not accept them for the purpose for
     which they were intended. "Absent a principal obligation created
     by the contemporaneous extension of credit by Cardinal to CMD, no
     acecessory obligation arose".

     The lines of credit eventually extended in 1976 were not relying
     on the guarantees submitted. The court notes that filling in the
     blanks in 1980 could not revive them. Further, Cardinal was
     unaware of the notes and could not have relied on them to their
     detriment. It is a stretch to think that the two men wanted to
     secure the debts of the company in perpetuity.

**** takeaway

*** Ambrose v. M & M Dodge, Inc.

**** facts

     A man receives a bad truck from Dodge/Chrysler. His lawyer
     negotiates a settlement and has documents which the man signs. On
     phone with Dodge, lawyer asks Dodge when they will pay off the
     loan which Dodge says is not part of the deal. Lawyer says there
     is no deal. Dodge argues that signing the documents concluded the deal.

**** lower court

     Agrees with plaintiff that there was never an acceptance because
     the documents were never received.

**** rule

     This contract requires a written acceptance.

     #+BEGIN_QUOTE
     A written revocation, rejection, or acceptance is received when
     it comes into the possession of the addressee or of a person
     authorized by him to receive it, or when it is deposited in a
     place the addressee has indicated as the place for this or
     similar communications to be deposited for him.
     #+END_QUOTE

**** holding

     No acceptance was received so there could be no effective
     acceptance of the deal.

**** reasoning

     This type of contract requires a written acceptance. 1938
     provides that acceptance is effective upon reception. Louisiana
     is a "reception theory" of contract formation, meaning that
     formation happens as soon as the instrument reaches the
     offeror. This has obviously never happened. The contract could
     not have been formed orally but /only/ upon receipt of the
     documents. Those never left the lawyer and thus could not
     possibly have been received by Dodge.

**** takeaway
*** Ever-Tite Roofing Corporation v. Green

**** facts

     Defendants contract for plaintiff to repair roof. Contract
     stipulates that it cannot be accepted by just anyone but by
     written acceptance by the principal or authorized officer of the
     Contractor or /upon commencing performance of the work/.

     Contractor got home office approval, credit check on defendant,
     and then set out to perform the work. The van arrived and
     defendant prevented workers from attempting the work as they had
     retained another crew to do the work.

**** lower court

     Ruled that the offer was revoked before it was accepted.

**** rule

     #+BEGIN_QUOTE
     When the offeror manifests an intent ot give th eofferee a delay
     within which to accept, without specifying a time, the offer is
     irrevocable for a reasonable time.
     #+END_QUOTE

**** holding

     Plaintiff had accepted by commencing performance. There was a
     valid contract and a breach.

**** reasoning

     Plaintiff had a reasonable amount of time to contemplate the
     offer. When plaintiff gathered materials and workmen in the
     morning, the work was commenced and under the terms of the
     contract there was acceptance by performance. Therefore the
     revocation came too late.

**** takeaway

*** National Co. v. Navarro

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

** Acceptance and Terms of the Offer

*** Rodrigue v. Gebhardt

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

** Form

*** Breaux Brothers Construction Company v. Associated Contractrs, Inc.

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway
*** Barchus v. Johnson

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

* Cause

** Cause as a Criterion for the Classification of Contracts

*** Spannier v. De Voe

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Succession of Lawrence

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Perry v. Perry

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Thielman v. Gahlman

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Louisiana College v. Keller

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Baptist Hospital v. Cappel

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

*** Flood v. Thomas

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway

* Applying the Theory of Cause (chapter vi)

** natural obligations

*** Thomas v. Bryant

**** facts

     A stepson signs a note promising to pay for half of alcohol
     abuse treatment. Son brings suit upon non-payment

**** lower court

     Finds for stepson that the debt is valid and enforceable

**** rule

     In order to create a "natural obligation" from a moral duty the
     following must be satisfied:
     1) The moral duty must be felt towards a particular person, not
        all persons in general
     2) The person involved feels so strongly about the moral duty
        that he truly feels he owes a debt
     3) The duty can be fulfilled through rendering a performance
        whose object is of pecuniary value
     4) A recognition of the obligation by the obligor must occur,
        either by performing the obligation or by promising to  to perform
     5) Fulfillment of the moral duty must not impair the public order

**** holding

     The debt is enforceable, as founded upon a moral duty that
     satisfied the above tests

**** reasoning

     1) The duty was owed to Bryan particularly
     2) He felt he owed a duty to his step-son and friend
     3) It had a monetary value
     4) He reocgnized the moral obligation by promising to perform
     5) Nothing abou tthis would impair public order

**** Dissent

     Argued that detrimental reliance would lead to the same
     conclusion. The promise was of the type to induce the person to
     rely. That person did rely to his detriment, incurring bills at
     the treatment facility. The reliance was reasonable to rely on a
     step-father and friend's promise to help pay for alcohol
     treatment.

**** takeaway

*** Wortmann v. French

**** facts

     In divorce, a man gives to his wife the house for $10 and other
     consideration and services. He was the cause of the divorce for
     living with his side corn at the time.

**** lower court

     Rules in favor of the husband. Husband argues that the contract
     was not founded upon a true consideration and therefore fails for
     lack of form being a gratuitous donation.

**** rule

     A moral obligation does not give grounds for one to demand
     performance, but like a shield, does allow for one to keep what
     has been donated.

     #+BEGIN_QUOTE
     No suit will lie to recover what has been paid, or given in
     compliance with a natural obligation.
     #+END_QUOTE

**** holding

     The house was given by the husband to make ammends for his
     behavior, a natural obligation. As such he cannot recover what
     has given even though his ex-wife had no legal claim to enforce
     the promise.

**** reasoning

     Policy reasons prevent suing on a marriage contract but the
     notion to make reparations still rises to a natural
     obligation. The $10 and services rendered was a ruse and this
     "sale" was predicated on the injury that the husband recognized
     he had caused his wife.

**** takeaway

*** Service Finance Co. Of Baton Rouge Inc. v. Daigle

**** facts

     A man owes a debt and goes through bankruptcy. His financial
     company contacts him and he says "would go ahead and continue
     paying as he had done before I received the notice [of
     bankruptcy]". He makes three payments after bankruptcy and then
     seems to stop.

**** lower court

     Rules in favor of the debtor. Financial services company appeals.

**** rule

     In order to revive a debt based on a moral obligation, an oral
     promise would suffice it must be "an express promise to pay the
     specific debt... [in a] clear, distinct, and unequivocal
     recognition and renewal of the debt as a binding obligation"
     Caselaw does not allow for interpreting payments as

**** holding

     The statements made are not a clear, distinct, and unequivocal
     renewal of the obliation.

**** reasoning

**** takeaway

*** Stoll v. Goodnight Corporation

**** facts

     A woman is a travel agent and accepts a bad check. Her employer
     points out in the manual where it states employees are
     responsible for these monies. She pays it back from salary
     deductions and then is fired after the debt is paid.

**** lower court

     She sues for her money back arguing that she never owed the money
     legally and it should be returned. the court finds for defendants
     and she appeals.

**** rule



**** holding

     Mrs. Stoll "freely paid her employer in resonse to her /natural
     obligation/ to do so and cannot reclaim the payment on the
     grounds that the obligation could not have been enforced by
     judicial action.

**** reasoning

     #+BEGIN_QUOTE
     Without inquiring whether she could have been held civilly
     responsible, Ms. Stoll agreed, ohwever reluctantly, to reimburse
     the agency for its loss. Ms. Stoll's payment obviously arose not
     from coercion but from "udty of conscience", the common
     demoninator of all natural obligations that distinguishes them
     from acts of charity.
     #+END_QUOTE

     Her perceived fear of losing her job was not sufficient to make
     the repayment involuntary or founded on error. It was freely
     performed. "She considered herself a debtor and the agency a
     creditor. After the fact of payment, under these circumstances,
     the accuracy of Ms. Stoll's evaluation of her legal liability to
     the agency is immaterial to the issue of whether the natural
     obligation was freely performed or paid voluntarily."

**** takeaway

** remission of debt

*** Hicks v. Hicks

**** facts

     Suit after death. Mother of defendant sold a house to
     defendant. Notes were returned saying services had been received
     as equivalent to cash.

**** lower court

     Plaintiff brings suit arguing that this was a donation that must
     fail for lack of form. Lower court agrees.

**** rule

     #+BEGIN_QUOTE
     The remission of the debt is either conventional, when it is
     expressly granted to the debtor by a creditor either having a
     capacity to alienate; Or tacit, when teh creditor voluntarily
     surrenders to his debtor the orginal title under private
     signature which establishes the obligation.
     #+END_QUOTE

**** holding

     The cancelled notes were a remission of the debt. Remission has
     no special form and therefore overrules the lower court.

**** reasoning

**** takeaway

*** Hurley v. Hurley

**** facts

**** lower court

**** rule

**** holding

**** reasoning

**** takeaway
