* Aug 29

** damage interests

1. expectancy
the benefit of the bargain. what you expected to gain by the promise
2. reliance
damages incurred upon reliance of the contract
3. restitution
remove the benefit that accrued to the promisor

when reliance are used:
when expectancy damages are difficult or impossible to quantify

** formula

loss in value + other loss - cost avoided - loss avoided

*** loss in value
 is the expectation value (the cost of the contract). if some performed, difference between where we're at versus the fulfilment position

*** other loss
incidentals and consequential

*** costs and loss avoided

** contemporary K law

*** change in K law

classic/formalist -> contemporary/realist

*** classic/formalist
- focus on coherent and well-defined rules
judges and scholars believed that law was essentially a science. box that would take info and spit out an answer.
- formalistic and rigid
- reflects support of free enterprise, private autonomy, and a laissez-faire system

*** contemporary/realist

move away from strict, rule based. to a consideration of doctrine and policy and process. torts, while policy plays a part, is still very rule based and formal. battery: a few pieces and get the output. but in K we have policies that suggest different rules.

- contractural relationships are just too complex and varied to be decided by some kind of rigid machine
- had to concern ourselves with the power of the bargaining players; power imbalance, business ethics, employment rights, etc.

what they suggested is that law needs to reflect social policy. the rules need to reflect the policy of the time. rules need to evolve as the society evolves. should be grounded in real applications to economics and the market.

no school swinging back to the original neo-formalist.

** definition

*** contract
a contract is a promise or a set of promises for the breach of which the law gives a remedy, or th eperformance of which the law in some way recognies as a duty.

the parties must intend to enter into a K relationship and agree to the terms, and the assent must be the kind the law will enforce.

*** promise

a promise is a manifestation of intention to act or refrain from acting in a specified way, so made as to justify a promisee in understanding that a commitment has been made

*** agreement

agreement: manifestation of mutual assent on the part of two or more persons.

bargain: is an agreement to exchange promises or to exchange a promise for a performance or to exchange performances.

bargain may or may not create an obligation; agreement is creating an obligation.

*** manifestation

manifestation of mutual assent to an exchange requires that each party either makes a promise or begin or render a performance

*** conduct as manifestation of assent

manifestation of assent may be made wholly or partly by written or spoken words or by other acts or failure to act.

the conduct of a party is not effective as a manifestation of his assent unless he intends to engage in the conduct and knows or has reason to know that the other party may infer from his conduct that he assents.

** objective

started in the formalist parts. there's no machine that can take into account the closely held secrets of the mind; however we can make simplified objective machines.

- don't want to bind someone who did not agree to be bound
- but balance that against the expectations of one who reasonably relied on the appearance of assent.

*** who is the reasonable person

between 1910 and 1954. they are male. they are white. they are 50s and above. socioeconomic back ground, they are at least middle class, upper middle class.

can look at probabilities, contracts of a similar circumstances. what do people expect when tey are buying a car? what do people expect when they get in a cab.

*** subjective part

look at the words used. in the context of the entire trasnactions, behavior. in certain circumstances look at custom and usage in the marketplace

objective test suggests a corresponding DUTY TO READ.
* aug 31

** offer
did they promise something by which they would be bound. did the oferee understand that the offeror wished to be bound and did they accept it∫ùéâo˝

1. communication
2. intend
3. oferee understanding that they will conclude it

types of contracts questions
1. formation

might get a hypo. was there a contract in the first place

start with mutual assent. was it formed

2. enforcement

now that we have a contract, no analysis if it wsa but a question about enforcement; voidable, capacity, fraud.

3. assuming contract and enforcable: breach and damages

how does a party breach,

*** objective standard

mutual assent. viewed from an objective standard. would a reasonable person have understood that an offer was made and that an offer was accepted.

use the behavior of the parties. the words said.

when there are special circumstances, we can leave the objective standard for the parties' subjective knowledge.

*** offer
an offer is the manifestation of willingness to enter into a bargain, so made as to justify another

*** certainty

term of K must be reasonably certainthe terms of K are certain

*** nebraska

1. statements of price are never enough to make an offer
2. not specific enough in quantity, might have less and can't fulfill contract or more and not be able to sell the small portion
3. lack of shipping details. seed co sent instructions to send immediately and asked about timeline

*** to whom addressed

in most instances looking for offers addressed to some kind of identifieable group of people. when offers are made to large part of gen public, we presume, (rebuttable presumption) that it is a solicitation for offers rather than an offer.

** prelim negotiations

   vast majority are non-binding. records the desire to work together and creates no obligation on either party.

   another type:
   binding as to the ultimate objection
- preliminary in form, but it is clear that the parties intent to be bound to their ultimate objective
- final agreement a formality
- must reflect agreement on all material terms

objective reflection that the parties intended to be bound. the contract memorializes the earlier agreement

binding as to negotiations in good faith
- commits the parties to continue to negotiation in good faith
- can be express or implied
- must be cleraly the intent of both parties

* sep 5

  in lefkowitz case, what kind of damages would you ask for?

  K: a K is a promies or a set of promises for the breach of which the law givesa remedy, or the performacne of which the law gives

** mutual assent
1. offer and acceptance
2. judged objectively

gonna look at language and the words used

** types of K

*** bilateral

    concern the mode of acceptance. in a bilateral, the acceptance on both sides is a promise. promise to pay x amount of money if you promise to pay x amount of money

*** unilateral

    when the offeror indicates that the only way the offeror will accept accceptance is through whatever is required of the other party. acceptance in a unilateral is full performance. so if you offer your house but only if they bring 100k tomorrow. ball is totally in their court. full performance by the offeree. different situation when its partial or started performance only.

*** option

    gives a timeframe but there is a separate consideration. leave an offer open but it creates no obligation. it is just an offer. unless we've created an option contract. in order to create the option contract there has to be additional consideration outside of the consideration for the promise itself. separate consideration to create the requirement. Lose power to revoke as the offeror

** mutual assent

   objective standard, words behavior

** advertisements

   open to the world, not specific

   also doesn't include the promisory language, just an invitation to go to the store and make an offer to buy.

   an advertisement will be an offer if the terms are specific, if we can clearly identity who has the right to accept and the promissory language

   the first come first serve is what made the ad different than other ads that are open to the public. 3 potential acceptors in that case (only 3 coats)

** prelim negotiations

   a manifestation of willingness to enter into a bargain is not an offer if the person to whom it is addressed knows or hsa reason to know that the person making it does not intend to conclude a bargain until he has made a further manifestation of assent.

   looking for language to demonstrate that parties have gone past negotiation to where party is making an offer and a party is making an acceptance.

1. identifiable terms
2. some type of promissory language
3. other types of outward manifestations, (PR release, etc)

*** empro

    created all sorts of outs for itself in the process. even if there was an offer (debatable) can't see a way that there was acceptance. sent back a letter saying we have more things to discuss.

*** arnold

    on one side, there's a letter saying we have an agreement ahead of it. on the other side we have press release, specific details down to office locations, financial stuff,

    a contract of this size and magnitude. is there expectatoin that everything will be written? what are the essential terms? factory, stock, management.

*** copeland

    agreement to agree is not enforceable: cant force someone into a contract, no guarantee of a final product.

**** good faith in negotiations versus in contract

     good behavior in negotiations

** wrap up

*** summary of contract parts

1. communication
2. offer must indicate a desire to into a K, which means terms must be included

terms and promissory language

3. must be directed at some person or group of persons

identifiable oferee
4. offer must invite acceptance


5. offer must provide a reasonable understanding that acceptance will create a K

we need to know who gets to accept. we know from fur case that we dont have to know the specific person i nthe world who gets to accept, it was the first person in the star who said i want the coat. an identifiable offeree.

*** random bits

    the offeror is the master of the offer. up to them to include these terms and add what they want.

*** considerations

1. most important::: the words of the potential offer,
   1. terms: comprehensive and specific
   2. words of promise of K
2. relationship between the parties
   1. strangers versus long time commerce
3. behavior of the party
   1. joking, issue of mutual assent
4. common practices and trade usage
   1. practices within a particular area. courts will look at practices of sales of grain to determine if there is a contract
5. anything else that is relevant

is there a K in the first place.
was there offer, was there acceptance, was there mutual assent.

when we are looking at enforcement, we don't get some of these anylonger, we are stuck inside the contract.

** revoking an offer

*** dodds and dickinson

    no consideration for the promise to keep it open so therefore the offeror has every right to revoke the offer up until the time of acceptance.

    by allowing the offeror to revoke an offer at any time before acceptance we try to put the parties on the same level. the oferree can walk away at any time. the only time we will enforce one of these is if its a promise bound by consideration.

    in order for dodds to win this case, he had to revoke the offer before dickinson accepted. if there was an offer out there and the offeree accepts, we immediately have a contract. dodds never revoked in person, the trip at night and the morning never had an official revocation. no direct revocation. was there an indirect revocation. did dodds take action such that he knew the offer was invalid.

    court does a subjective analysis, the "one mind" so to speak. however, this case would still survive the objective analysis. Because Dickinson had knowledge that the property had sold and no reasonable person would have thought the offer had no been revoked.

*** when can you revoke?

    at any time before it is accepted. exceptions: options K (time is left open and have separate consideration to leave the time open) or firm offers, something to do with merchants.
* sep 7

** review offer
   manifestatoin of willingness to enter bargain so made

   to have
1. communication
2. offer has to indicate the desire to enter the contract (intent...)
3. directed at some person or group of persons
4. offer must invite acceptance
5. must give the reasonable understanding that acceptance will complete the contract


considerations: the words of the contract

offeror can revoke the offer before it is accepted. is the master of hte contract. an offer is revoked if a reasonable time has passed without acceptance.

an effective revoca
- communication, direct or indirect
- effective receipt
- words or actions inconsistent with the continued intent to enter a K

exceptions:
- option K
- firm offers

in these, power to revoke is limited or non-existent.

*** hypo:
1. is there a valid offer? if so, what is that offer?

   1. communication, phone calls, written letter

   2. has to indicate the desire to enter the contract: "offering to sell"

   3. directed: to the niece

   4. invite acceptance: reaching out for agreement

   5. acceptance will complete:

2. acceptance?

   1. assent to the specific terms of the offer: no counter arguing, accepted the terms as is

3. mutual assent?

   1. objectively agreeing to enter the K.

became valid the moment the landlord approved the lease.


** acceptance

   offeree has ability to accept, reject, or counteroffer

*** ways to terminate (R 36)

- rejection of the offer by offeree
- counter offer
- lapse
- revocation by offeror
- death or incapacity of offeror or offeree
- non-occurrence of any conditions accepted under the terms of the offer

*** is

- offeree's manifestation of assent to the offer
- brings K into existence (assuming ther
- definite and unequivocal
- volitional act
- objective analysis (judge acceptance by a reasonable person standard)

*** hypo

    valid revocation since he communicated directly and made it known he had no desire to enter into a contract.

*** mirror image rule

    at the stage of promise to promise. we dont' get the mirror muddy, so to speak. the parties accept the terms of which the offer was made.

*** ardente v horan

    defendants say send us bids. why not an offer: lacks specific audience, no clear intent to enter into a contract, not clear that acceptance would bind the bid offerors, terms are not clearly identified.

    the the plaintiff makes a bid, is that a K? Court treats it as if its not. because we would have had a K immediately. Bid does not identify when, and some other essential terms. The purchase agreement that D send back to P is the essential offer. So D makes the offer.

    Given that the purchase agreement is an offer, it is on the P to accept. But he attaches a letter with what the court calls additional requirements. by asking to "confirm" part of the trasnaction so the court treats as a counter offer which the D can then reject.

    Court notes that there can be counter arguments but they cannot be essential to the main deal but separately negotiated. Court suggests that if different language had been used in this letter it could be have been treated as a separate negotiation.

**** restatement 61

     an acceptance which requests a change or addition to the terms of the offer is not thereby invalidated unless the acceptance is made to depend on an assent to the changed or added terms.

*** mailbox rule

    2nd rule related to acceptance. acceptance is effective upon dispatch. the moment it is put in the mailbox as long as it has proper postage and right address. exception, option K where acceptance not effective until receipt.

    the offeror has every opportunity to change this rule and is subject to it unless he makes other terms. For Option K it is upon receipt because the offeror is not free to rescind his offer anyways because of the consideration given.

*** means of acceptance

    offer may invite or require acceptance in a certain master. offeror is the master of the offer. if offeror wants written documentation, whatever, it is the offerors bargain.

    if no means of accetpance is specified, it will be based on reasonableness and relationship between the parties.

    for bilateral K: acceptance usually by promise
    for unilateral K: acceptance by performance

**** acceptance by performance (R 54)

     If the offer invites acceptance by performance, the offeree does ont need to ontify the offeror of the acceptance

     BUT, if the offeree knows the offeror has _no adequate means_ of leaning of the performance/acceptance with reasonable promptness and certainty, the offeror's contractual duty is discharged unless

- offeree exercised resaonable diligence to notify
- offeror learned of the performance

*** white v corlies & tifft

    Breach of K action. "Upon an agreement to finish the fitting up of offices in two weeks from date, you can begin at once." So what makes him think performance was expected? "begin at once". seemed to have reached an agreement, asked for assent, signed and returned it. So from P point of view we can begin at once. P buys lumber and begins working.

    why did the court say . court said even if performance was acceptable, the D didn't perform the _contract_ necessarily. Does this contract invite acceptance by performance? It says "upon agreement". This case has stood the test of time for the proposition that "unless performance is invited, starting performance at any level is not going to necessarily create a K". If performance is invited, then even partial performance is going to bind the parties.

*** petterson v pattberg

    clearly invites acceptance by performance. the fact that the brief case hadn't changed hands precluded it. you see someone walking up and you can revoke it at any time. the court suggests that when the performance is gonna be  part of the bargain, there is a corresponding duty on the offeror to accept the performance (this is in the dissent).

*** hypo

    while waiting in line to open an account with a bank. if you wait for over 5 minutes in line they give you $5 and the offer can be withdrawn at any time. manager takes down the poster right before you hit the time limit.

**** creation of an option K

1. consideration for the promise not to revoke for a sepcified time
2. part performance or tender
   1. offer does not invite prmoissory acceptance
   2. offer invites acceptance by performance
   3. option K created when the offeree egins the invited performance or tenders a beginning of it.

when there's partial performance we get an option contract

*** hobbs

series of transactions, done in a particular way. sent skins, received payments. sent skins in, heard nothing and then several months. silence looks a lot like assent.

**** acceptance by silence

acceptance by silence is limited:
- when offeree takes the benefit of offered services with reasonable opportunity to reject them & knows compensation is expected
- offeror gave offeree reason to understand that seent may be manifested by silence or inaction

** electronic
