* Aug 29

** damage interests

1. expectancy
the benefit of the bargain. what you expected to gain by the promise
2. reliance
damages incurred upon reliance of the contract
3. restitution
remove the benefit that accrued to the promisor

when reliance are used:
when expectancy damages are difficult or impossible to quantify

** formula

loss in value + other loss - cost avoided - loss avoided

*** loss in value
 is the expectation value (the cost of the contract). if some performed, difference between where we're at versus the fulfilment position

*** other loss
incidentals and consequential

*** costs and loss avoided

** contemporary K law

*** change in K law

classic/formalist -> contemporary/realist

*** classic/formalist
- focus on coherent and well-defined rules
judges and scholars believed that law was essentially a science. box that would take info and spit out an answer.
- formalistic and rigid
- reflects support of free enterprise, private autonomy, and a laissez-faire system

*** contemporary/realist

move away from strict, rule based. to a consideration of doctrine and policy and process. torts, while policy plays a part, is still very rule based and formal. battery: a few pieces and get the output. but in K we have policies that suggest different rules.

- contractural relationships are just too complex and varied to be decided by some kind of rigid machine
- had to concern ourselves with the power of the bargaining players; power imbalance, business ethics, employment rights, etc.

what they suggested is that law needs to reflect social policy. the rules need to reflect the policy of the time. rules need to evolve as the society evolves. should be grounded in real applications to economics and the market.

no school swinging back to the original neo-formalist.

** definition

*** contract
a contract is a promise or a set of promises for the breach of which the law gives a remedy, or th eperformance of which the law in some way recognies as a duty.

the parties must intend to enter into a K relationship and agree to the terms, and the assent must be the kind the law will enforce.

*** promise

a promise is a manifestation of intention to act or refrain from acting in a specified way, so made as to justify a promisee in understanding that a commitment has been made

*** agreement

agreement: manifestation of mutual assent on the part of two or more persons.

bargain: is an agreement to exchange promises or to exchange a promise for a performance or to exchange performances.

bargain may or may not create an obligation; agreement is creating an obligation.

*** manifestation

manifestation of mutual assent to an exchange requires that each party either makes a promise or begin or render a performance

*** conduct as manifestation of assent

manifestation of assent may be made wholly or partly by written or spoken words or by other acts or failure to act.

the conduct of a party is not effective as a manifestation of his assent unless he intends to engage in the conduct and knows or has reason to know that the other party may infer from his conduct that he assents.

** objective

started in the formalist parts. there's no machine that can take into account the closely held secrets of the mind; however we can make simplified objective machines.

- don't want to bind someone who did not agree to be bound
- but balance that against the expectations of one who reasonably relied on the appearance of assent.

*** who is the reasonable person

between 1910 and 1954. they are male. they are white. they are 50s and above. socioeconomic back ground, they are at least middle class, upper middle class.

can look at probabilities, contracts of a similar circumstances. what do people expect when tey are buying a car? what do people expect when they get in a cab.

*** subjective part

look at the words used. in the context of the entire trasnactions, behavior. in certain circumstances look at custom and usage in the marketplace

objective test suggests a corresponding DUTY TO READ.
* aug 31

** offer
did they promise something by which they would be bound. did the oferee understand that the offeror wished to be bound and did they accept itºŽ‰oý

1. communication
2. intend
3. oferee understanding that they will conclude it

types of contracts questions
1. formation

might get a hypo. was there a contract in the first place

start with mutual assent. was it formed

2. enforcement

now that we have a contract, no analysis if it wsa but a question about enforcement; voidable, capacity, fraud.

3. assuming contract and enforcable: breach and damages

how does a party breach,

*** objective standard

mutual assent. viewed from an objective standard. would a reasonable person have understood that an offer was made and that an offer was accepted.

use the behavior of the parties. the words said.

when there are special circumstances, we can leave the objective standard for the parties' subjective knowledge.

*** offer
an offer is the manifestation of willingness to enter into a bargain, so made as to justify another

*** certainty

term of K must be reasonably certainthe terms of K are certain

*** nebraska

1. statements of price are never enough to make an offer
2. not specific enough in quantity, might have less and can't fulfill contract or more and not be able to sell the small portion
3. lack of shipping details. seed co sent instructions to send immediately and asked about timeline

*** to whom addressed

in most instances looking for offers addressed to some kind of identifieable group of people. when offers are made to large part of gen public, we presume, (rebuttable presumption) that it is a solicitation for offers rather than an offer.

** prelim negotiations

   vast majority are non-binding. records the desire to work together and creates no obligation on either party.

   another type:
   binding as to the ultimate objection
- preliminary in form, but it is clear that the parties intent to be bound to their ultimate objective
- final agreement a formality
- must reflect agreement on all material terms

objective reflection that the parties intended to be bound. the contract memorializes the earlier agreement

binding as to negotiations in good faith
- commits the parties to continue to negotiation in good faith
- can be express or implied
- must be cleraly the intent of both parties

* sep 5

  in lefkowitz case, what kind of damages would you ask for?

  K: a K is a promies or a set of promises for the breach of which the law givesa remedy, or the performacne of which the law gives

** mutual assent
1. offer and acceptance
2. judged objectively

gonna look at language and the words used

** types of K

*** bilateral

    concern the mode of acceptance. in a bilateral, the acceptance on both sides is a promise. promise to pay x amount of money if you promise to pay x amount of money

*** unilateral

    when the offeror indicates that the only way the offeror will accept accceptance is through whatever is required of the other party. acceptance in a unilateral is full performance. so if you offer your house but only if they bring 100k tomorrow. ball is totally in their court. full performance by the offeree. different situation when its partial or started performance only.

*** option

    gives a timeframe but there is a separate consideration. leave an offer open but it creates no obligation. it is just an offer. unless we've created an option contract. in order to create the option contract there has to be additional consideration outside of the consideration for the promise itself. separate consideration to create the requirement. Lose power to revoke as the offeror

** mutual assent

   objective standard, words behavior

** advertisements

   open to the world, not specific

   also doesn't include the promisory language, just an invitation to go to the store and make an offer to buy.

   an advertisement will be an offer if the terms are specific, if we can clearly identity who has the right to accept and the promissory language

   the first come first serve is what made the ad different than other ads that are open to the public. 3 potential acceptors in that case (only 3 coats)

** prelim negotiations

   a manifestation of willingness to enter into a bargain is not an offer if the person to whom it is addressed knows or hsa reason to know that the person making it does not intend to conclude a bargain until he has made a further manifestation of assent.

   looking for language to demonstrate that parties have gone past negotiation to where party is making an offer and a party is making an acceptance.

1. identifiable terms
2. some type of promissory language
3. other types of outward manifestations, (PR release, etc)

*** empro

    created all sorts of outs for itself in the process. even if there was an offer (debatable) can't see a way that there was acceptance. sent back a letter saying we have more things to discuss.

*** arnold

    on one side, there's a letter saying we have an agreement ahead of it. on the other side we have press release, specific details down to office locations, financial stuff,

    a contract of this size and magnitude. is there expectatoin that everything will be written? what are the essential terms? factory, stock, management.

*** copeland

    agreement to agree is not enforceable: cant force someone into a contract, no guarantee of a final product.

**** good faith in negotiations versus in contract

     good behavior in negotiations

** wrap up

*** summary of contract parts

1. communication
2. offer must indicate a desire to into a K, which means terms must be included

terms and promissory language

3. must be directed at some person or group of persons

identifiable oferee
4. offer must invite acceptance


5. offer must provide a reasonable understanding that acceptance will create a K

we need to know who gets to accept. we know from fur case that we dont have to know the specific person i nthe world who gets to accept, it was the first person in the star who said i want the coat. an identifiable offeree.

*** random bits

    the offeror is the master of the offer. up to them to include these terms and add what they want.

*** considerations

1. most important::: the words of the potential offer,
   1. terms: comprehensive and specific
   2. words of promise of K
2. relationship between the parties
   1. strangers versus long time commerce
3. behavior of the party
   1. joking, issue of mutual assent
4. common practices and trade usage
   1. practices within a particular area. courts will look at practices of sales of grain to determine if there is a contract
5. anything else that is relevant

is there a K in the first place.
was there offer, was there acceptance, was there mutual assent.

when we are looking at enforcement, we don't get some of these anylonger, we are stuck inside the contract.

** revoking an offer

*** dodds and dickinson

    no consideration for the promise to keep it open so therefore the offeror has every right to revoke the offer up until the time of acceptance.

    by allowing the offeror to revoke an offer at any time before acceptance we try to put the parties on the same level. the oferree can walk away at any time. the only time we will enforce one of these is if its a promise bound by consideration.

    in order for dodds to win this case, he had to revoke the offer before dickinson accepted. if there was an offer out there and the offeree accepts, we immediately have a contract. dodds never revoked in person, the trip at night and the morning never had an official revocation. no direct revocation. was there an indirect revocation. did dodds take action such that he knew the offer was invalid.

    court does a subjective analysis, the "one mind" so to speak. however, this case would still survive the objective analysis. Because Dickinson had knowledge that the property had sold and no reasonable person would have thought the offer had no been revoked.

*** when can you revoke?

    at any time before it is accepted. exceptions: options K (time is left open and have separate consideration to leave the time open) or firm offers, something to do with merchants.
* sep 7

** review offer
   manifestatoin of willingness to enter bargain so made

   to have
1. communication
2. offer has to indicate the desire to enter the contract (intent...)
3. directed at some person or group of persons
4. offer must invite acceptance
5. must give the reasonable understanding that acceptance will complete the contract


considerations: the words of the contract

offeror can revoke the offer before it is accepted. is the master of hte contract. an offer is revoked if a reasonable time has passed without acceptance.

an effective revoca
- communication, direct or indirect
- effective receipt
- words or actions inconsistent with the continued intent to enter a K

exceptions:
- option K
- firm offers

in these, power to revoke is limited or non-existent.

*** hypo:
1. is there a valid offer? if so, what is that offer?

   1. communication, phone calls, written letter

   2. has to indicate the desire to enter the contract: "offering to sell"

   3. directed: to the niece

   4. invite acceptance: reaching out for agreement

   5. acceptance will complete:

2. acceptance?

   1. assent to the specific terms of the offer: no counter arguing, accepted the terms as is

3. mutual assent?

   1. objectively agreeing to enter the K.

became valid the moment the landlord approved the lease.


** acceptance

   offeree has ability to accept, reject, or counteroffer

*** ways to terminate (R 36)

- rejection of the offer by offeree
- counter offer
- lapse
- revocation by offeror
- death or incapacity of offeror or offeree
- non-occurrence of any conditions accepted under the terms of the offer

*** is

- offeree's manifestation of assent to the offer
- brings K into existence (assuming ther
- definite and unequivocal
- volitional act
- objective analysis (judge acceptance by a reasonable person standard)

*** hypo

    valid revocation since he communicated directly and made it known he had no desire to enter into a contract.

*** mirror image rule

    at the stage of promise to promise. we dont' get the mirror muddy, so to speak. the parties accept the terms of which the offer was made.

*** ardente v horan

    defendants say send us bids. why not an offer: lacks specific audience, no clear intent to enter into a contract, not clear that acceptance would bind the bid offerors, terms are not clearly identified.

    the the plaintiff makes a bid, is that a K? Court treats it as if its not. because we would have had a K immediately. Bid does not identify when, and some other essential terms. The purchase agreement that D send back to P is the essential offer. So D makes the offer.

    Given that the purchase agreement is an offer, it is on the P to accept. But he attaches a letter with what the court calls additional requirements. by asking to "confirm" part of the trasnaction so the court treats as a counter offer which the D can then reject.

    Court notes that there can be counter arguments but they cannot be essential to the main deal but separately negotiated. Court suggests that if different language had been used in this letter it could be have been treated as a separate negotiation.

**** restatement 61

     an acceptance which requests a change or addition to the terms of the offer is not thereby invalidated unless the acceptance is made to depend on an assent to the changed or added terms.

*** mailbox rule

    2nd rule related to acceptance. acceptance is effective upon dispatch. the moment it is put in the mailbox as long as it has proper postage and right address. exception, option K where acceptance not effective until receipt.

    the offeror has every opportunity to change this rule and is subject to it unless he makes other terms. For Option K it is upon receipt because the offeror is not free to rescind his offer anyways because of the consideration given.

*** means of acceptance

    offer may invite or require acceptance in a certain master. offeror is the master of the offer. if offeror wants written documentation, whatever, it is the offerors bargain.

    if no means of accetpance is specified, it will be based on reasonableness and relationship between the parties.

    for bilateral K: acceptance usually by promise
    for unilateral K: acceptance by performance

**** acceptance by performance (R 54)

     If the offer invites acceptance by performance, the offeree does ont need to ontify the offeror of the acceptance

     BUT, if the offeree knows the offeror has _no adequate means_ of leaning of the performance/acceptance with reasonable promptness and certainty, the offeror's contractual duty is discharged unless

- offeree exercised resaonable diligence to notify
- offeror learned of the performance

*** white v corlies & tifft

    Breach of K action. "Upon an agreement to finish the fitting up of offices in two weeks from date, you can begin at once." So what makes him think performance was expected? "begin at once". seemed to have reached an agreement, asked for assent, signed and returned it. So from P point of view we can begin at once. P buys lumber and begins working.

    why did the court say . court said even if performance was acceptable, the D didn't perform the _contract_ necessarily. Does this contract invite acceptance by performance? It says "upon agreement". This case has stood the test of time for the proposition that "unless performance is invited, starting performance at any level is not going to necessarily create a K". If performance is invited, then even partial performance is going to bind the parties.

*** petterson v pattberg

    clearly invites acceptance by performance. the fact that the brief case hadn't changed hands precluded it. you see someone walking up and you can revoke it at any time. the court suggests that when the performance is gonna be  part of the bargain, there is a corresponding duty on the offeror to accept the performance (this is in the dissent).

*** hypo

    while waiting in line to open an account with a bank. if you wait for over 5 minutes in line they give you $5 and the offer can be withdrawn at any time. manager takes down the poster right before you hit the time limit.

**** creation of an option K

1. consideration for the promise not to revoke for a sepcified time
2. part performance or tender
   1. offer does not invite prmoissory acceptance
   2. offer invites acceptance by performance
   3. option K created when the offeree egins the invited performance or tenders a beginning of it.

when there's partial performance we get an option contract

*** hobbs

series of transactions, done in a particular way. sent skins, received payments. sent skins in, heard nothing and then several months. silence looks a lot like assent.

**** acceptance by silence

acceptance by silence is limited:
- when offeree takes the benefit of offered services with reasonable opportunity to reject them & knows compensation is expected
- offeror gave offeree reason to understand that seent may be manifested by silence or inaction

** electronic

* sep 12

** review of mutual assent

considerations for mutual assent. objective analysis, just a little bit of subjective tinge

offer
- communication
- substance
  - intent/promise language, essential terms, invite acceptance
- directed at an identifieable perso nor group

acceptance
- communication
- manifestation of assent
- definite & unequivocal
rejcetion
counter offer

** hypos

lost your dog and post the following around the neighborhood: Lost Dog $100 cash reward

ignoring any issues of consideration, is this a valid offer?

*** COMMENT remember for offer
1. communication
2. offer has to indicate the desire to enter the contract (intent...)
3. directed at some person or group of persons
4. offer must invite acceptance
5. must give the reasonable understanding that acceptance will complete the contract

*** hypo 1 (original)

is it an offer? It is a communication, is a desire to to enter a contract, directed at the neighborhood, invites acceptance, gives reasonable understanding that acceptance will complete the contract.

would a reasonable person understand this? what condition of the dog, for information about the dog.

relating to who its offered to (specific audience): while it looks broad, the offer can only extend to the person who has the dog.

*** good samiritan finds it w/o knowledge of the poster

no contract. lack of a

*** hypos 3

you realize a close friend is going through a hard time, and you say, "I will lend you $500 if you promise to pay it back plus 5 percent interest

your friend thanks you and says "that's great, but can we make it Nov 2 so my paycheck


rule about communication. if no rule on how to accept. if the offer does not specify how to do acceptance rule is: "reasonable means of acceptance"

without knowing original offeror,

*** hypo 4

1. if you're doing an analysis, communication, terms, audience, you will miss money.
2. essential terms
3. promisorry language as opposed to solicitation for ofers, what language invites acceptance

its an effective K. I give you baseball collection, you give me $10,000, dictates type of acceptance required, and the time.

bilateral K. even though requested acceptance through performance. the performance requested doesn't have anything to do with the terms of the contract. nothing at all to do with the transaction.

is the tattoo the only way you can accept my offer?

have not limited acceptance to the cubs tattoo on the forehead, can still accept the K without the tattoo. "acceptance will be manifest" look for limiting acceptance.


*** hypo 5

alex send becky a letter

both parties send a letter to the offer offering identical terms for sale of property. but we have two offers so no possibility of acceptance

*** hypo 6

sell car for 1200. "I accept and want you to put new tires on it"

do we have acceptance or counteroffer?

think its acceptance and new bargin. in previous case, it was worded as "confirm", no conditional language here.

** creation of an option K

two ways to create
*** to pay consideration to keep the contract open

if we enter into a contract, give money to keep the offer open for the week, offer is required to held open

*** part performance or tender

partial payment WHEN the acceptance method is performance.

** electronic contracts

*** terms

**** box-top terms

     terms that you find when you went into the store and there were terms on the box product. courts likely to enforce because party had notice of the box-top terms because its on the outside of the box and you would have had the opportunity to read through those terms before you purchased or used when you got home

**** shrinkwrap terms

     inside the packaging so courts are less likely to apply those terms unless they are the types of terms a reaonable person would expect in those types of things. buyer doesn't have the opportunity to read through before purchasing.

**** brosewrap terms

     somewhere on the website and you have to browse to find them. perhaps at bottom or a link to terms and conditions.

**** clickwrap terms

     the "i accept", affirmative step. require user to do some physical manifestation by clicking and in the course of using the site.

*** considerations for electronic K

    courts will weigh these in each case, no one is particularly dispositive

**** conspicuousness

     location, color, size, hidden, prominent

**** notice

     while some overlap, explicit step, buying something do you see it as part of checkout

**** reasonable expectations

     what do we expect to find in these boilerplate provisions. arbitration agreements (these are found by courts to be reasonable), choice of law,

** register.com v verio

   verio argues that they never agreed to the terms. court says that while that argument works on the first query, after the first one they had knowledge of the conditions of the deal and they continued to take the fruits of the deal.

   uses an analogy to a farm stand and takes an apple, see a sign saying pay for the apple as you are leaving. no notice for the requirement to pay for the apple until after the transaction.

   going back to the fur coat case, was turned away on the coat. there there were different ads and house rules each time whereas here we have the same offer and same conditions each time

** nguyen v barnes and noble

   do we know that terms are at the bottom of th epage these days?

   an issue with acceptance.

   in 2017, knowing what we know,

* sep 14

** terms in a K

*** proimisorry terms

    the essential terms of the K. what did they promise to form the K

*** conditions

    a condition is a term i na K whose outcome is not clearly determined at the time of contract. condition to the contract, but if this condition does not happen then neither one on the hook for the K. we think of something that the parties have no control over and have no control over.

*** promissory conditions

    very little time, more complicated. conditions for which one of the parties may hav esome promissory control over. often times when buying real estate or car there's a financing requirement. so part is promising to get the right type of financing. you don't know for sure if that's something you can do.

*** other terms

** electronic contract considerations

*** conspicuousness

    bolded, packaging, where is it

*** notice

    popup, actual step

*** reasonable expectatoins

    things we would expect from any software.

*** knowledge

    the court wsa really concerned with whether the parties knew the terms. so its really how the first three create the fourth.

** contracting by automation

- buyer uses an automated system to place orders
- seller uses an automated system to take orders
- mutual assent?

court is considering automated systems.

how do we establish mutual assent when we have no parties directly involved with the transaction

*** arguments that there can be no mutual assent

- cant be meeting of the minds since there are no minds.

*** that there can be mutual assent

- courts have said they won't judge mutual assent at the time of contracting but the human decisions when setup to do the K'ing. the key is they have to match.

** Interpretation

*** Preliminary matters

**** interpretation v construction

     differences. interprtatoin: inferring meanings from facts. when interpreting, looking at what the parties, said, did, interaction, assess credibility, who do we believe more. its a faction analysis. in construction, we are inferring meaning as a matter of law. when looking at construction its one of those situations where its clear that one of the parties intended to contract but they left something out that neither party thought about and so now we have to use rules of construction to fill in the missing terms that they would have otherwise agreed to.

**** distinction

     distinction between this. and appellate has different standards between the two. appellate courts can review questions of law using an abuse of review standard and in many cases can review /de novo/. So there is a better liklihood of an appellate court changing questions of law rather than questions of fact. appellate courts have a much harder time changing facts. they acknowledge they didn't see or hear the witnesses, cold record, don't even get necessarilly as much evidence. trust the fact finder.

***** questions of law

      not gonna be based on a fact pattern. how a particular rule functions. outside of K, questions related to the constitutionality of a statute.

***** questoins of fact

      a question of fact is was this an offer. does this thing fit the elements required for an offer

**** interpretation

1. start with the words use
2. look to the normal and accepted meaning of those terms
3. context in which the words were used - K as a whole
4. negotation discussion & conduct
5. course of performance - actions after K formed
6. course of dealing - conduct in previous dealings
7. customs and usage

**** ambiguous vs vague terms

     ambiguous: more than one reasonable meaning. if terms are ambiguous and they can't agree, court will toss out the K. Vagueness is different

     vague: the breadth of a term.

     "objective approach with a significant subjective twist".

***** difference

      ambiguous, looking at a term that could have 2 or more meanings. a vague term could cover a big range.

**** latent v patent ambiguity

     latent: does not readliy appear in the communication

     patent: is apparent in the communication

**** consideratoins for ambiguous K

***** no party aware of the ambiguity

generally no K

unless both parties intended the same meaning

***** both parties were aware of the ambiguity but didn't talk about it

find no K

it doesn't make sense to grant one parties meaning over the other parties.

***** only one party aware of the ambiguity

generally K enforced based on the non-aware party's terms

*** raffles v wichelhaus

"mutual mistake"

contract for the sale of cotton to arrive on "Peerless" from bombar.

lower court says you got your cotton on a boat from bombay. pay up. appellate court says there was no "meeting of the mind" because they never agreed on which boat. There is a much more subjective standard. court decides that this fails at formation. from a reasonable point of view, was there mutual assent? from an objective point of view it seems like there was mutual assent.

*** oswald v allen

"mutual mistake"

dfeendant has two coin collections. one called swiss collection, one rare collection, but has swiss coins in both. plaintiff looks at the swiss coin collection and is shown a safety deposit box. looks at the swiss coins in the rarity collection as well. enter into an agreement. wsa gonna sell the swiss coin collection for $50k but P thought he was buying all of the swiss coins across both collections but D thought she was only selling the swiss collection and keeping the rare collection in total

court decides that there was no K and upholds the lower court ruling. same ruling as in previous case, there was no meeting of the minds, etc.

what are the promissory terms of this K? money for coins. unlike in previous K, concerned about promissory term, an essential term in this K whereas we were looking at a smaller term in the original K. we get to the same result in both, but is that right?

**** ambiguous

when ambiguous we are looking to see what the parties knew. if both parties are in the dark, NO K.

what about if in the dealings, there was correctoin of ambiguous terms. "the courts gonna find a K but on whose terms?. Gonna find under allen (the old lady). during correction, its clear to both sides the other side wants the other. they are aware of the ambiguity and both choose the opposite sides and therefore no K"

*** restatements 200 & 20245

**** goal

ascertaining the meaning of the promise or agreement

what did the parties K to?

**** restatement 201 different meanings

have the praties attached differemtn meanings?

if no, then the shared meaning is applied.

if yes, did 1 part know or have reason to know that th eother party attached a different meaning while the other party did not?

if yes the meaning attached by the "other party"
if no then probably no K.

*** Weinberg v. Edelstein

"vague terms"  what is a dress

P's lease from 1949 provided they could sell dresses coats and suits. landlords promised ont to permit other tennants to sell ladies dresses coats and suits.

D's lease took over someone in 1950

sold hosiery, gloves, lingerie, bras... and they knew of the restrictive covenant in P's ease.

problem comes about when D sells skirts and tops that could be worn together but didn't have to be. the restrictive covennt are legal part of an agreement where use of land or whatever you're using is restricted in some way.

procedurally P sues for injunction against D. this is the merits part after an injunction. so we take our time. what did these parties understand what a dress was. both definitions fit the. so next look at industry definitions. lots of manufacturing in US and could look at unions and looked at dictionary, looked at recent style trends. and the style was changing while the K was made and they had the chance to update the language but they did not.

holding that the D was not selling dress. D could not compel the customer to buy both. injunction was denied, can't advertise as pairs, can't sell as pairs, can't price as pairs.

how does the court make that determination. when does it stop? how does it try to resolve this. will look beyond the K to find the meaning thats most reasonable. "I don't want to do damage. gonna attempt to interpret it in a way that is consistent with our tools and does the most justice for both parties"

*** frigaliment importing

"chicken case"

P: chicken  = young chicken, broiling and frying
D: chicken = more inclusive, includes older stewing chicken


court steps

1. dictionary def: both sides supported
2. usda regulations : supported both sides
3. terms of the K was a whole.
   1. supported the seller.
   2. price of a larger bird was lower than smaller bird suggesting lower quality and K would include another price
4. context of the dealing: did not clearly support either party
5. course of performance :
   1. did not clearly support either party
   2. no common intention (although acknowledging that the buyer protested for the first shipment, but accepted that and continued accepting further shipments without complaint)

now can't decide, and follows lower court. buyer had the burden, buyer failed to meet that burden

takeaway. courts are going to again, don't have to have a clear answer. gonna look totality of the circumstances. it the court could have found a dictionary definition the court may have stopped there.

*** ucc article 2: sale of goods

sale: passing of _title_ from the seller to the buyer for a price
goods: movable things, including manufactured goods, livestock, and growing crops

NOT limited to merchants, but there are special rules when the transaction involves a merchant

applies to the sale of goods. in order to have the sale of goods you have to have a passing of a title form one to another. every time you go to a store you get a title transfer. every time you sell a textbook UCC applies.

** readings

tuesday

*** filling in the gaps384-398

*** form ks 408-419

*** start battle of forms 419-436

thursday

*** finish battle of forms 419-436

*** late terms 436 - 449

*** start parol evidence 451 - 468
* sep 19

** considerations for ambiguous K

*** no party aware of the ambiguity

    generally no K unless both parties intended the same meaning

*** both parties aware of the ambiguity

    generall no K unless both parties intended the same meaning

*** only one party aware

    generally K enforced based on the non-aware party's terms

    might be questions of bad faith, if party was aware and did not do anything, look at the non-aware party as the more innocent and interpret it from their point of view.

    all has to be reasonable.

** vague

*** can be cured

    one way to cure is partial performance.

*** if no cure

**** start with parties meanings

     was there a subjective understanding:

1. start with words of the K
2. course of negotations
3. course of performance
4. course of dealing

**** if no subjective agreement, there is a misunderstanding

1. does one party know or have reason to know the other party attached a different meaning>
   1. if so, assent & meaning of ignorant party
2. objective meaning
   1. plain and ordinary
   2. course of performance
   3. course of delaing
   4. usage of trade
3. if no objective meaning, the term is objectively vauge (chicken case?)

**** general rules of construction

- K construed as a whole
- ordinary meaning -- unless clearly shown to mean technical
- inconsistent provisions -- negotiated over standard
- preference to construe K as valid and enforceable
- ambiguity against party preparing K

K law comes from courts of equity rather than courts of law. always trying to get to fairness rather than super tight rules of construction. related to equity and fairness.

** filling in the gaps

*** background

   all manifestations of assent are inevitably incomplete

   how do we justify gap-filling? parties intended to K /and/ there is a reasonably certain basis for giving a remedy.

   CL will never fill in price for real estate whereas UCC can.

   UCC (majority): courts can supply reasonable terms for those missing: /ONLY/ when they are consistent with intent as otherwise expressed.

   courts don't want to add terms unless it looks like they meant to and the K fails if they don't.

*** sun printing

    open issues: price to pay and length of time that price governs

    if price only, we could rectify. but the problem was the K left out time as well. an option K would be enforced against D, but P would not be similarly bound. Plaintiff could choose to purchase that month, but then the next month the defendant could abstain.

    arguably the P is trying to do is saying by accepting the Canadian standard they are trying to cure by concession. takes the best price for the defendant. but court doesn't accept because the best price for defendant always depends upon the length of time. the plaintiff would be able to choose. but D's money is in the length of time. they speculate on the price and lock it in. this removes the speculative power of the D and vests it solely in the P.

    problem is that Plaintiff did not concede enough to win. P can walk away when the price rises but gets the benefit when the price decreases.

** illusory promises

*** requirements and output K

    buy agrees to buy everything that the seller produces. requirements seller responds to the buyer requests. eastern airlines and the radiator cases. don't identify a specific quantity. quantity can't be unreasonably disproportionate. took a really long time for courts to enforce these. what are the obligations. no evidence of mutual assent when there's no range of what they are obligated to.

*** iron case

    you're free to K, and you made a bad K. but it was reasonable. obligation of good faith and fair performance. if the other party was speculating, then we might find a breach.

*** gas case

*** lucy lady

** form K

*** carnival

    look at this K under the lens of fundamental fairness. don't care that they can't afford to go to florida. no evidence of bad faith. no fraud, no overreaching, D's had notice and had option to reject K if they didn't like the terms.

*** caspi v microsoft
