* oct 18
** hypo 1
** purpose and audience

   if you don't care about these you shouldn't be writing.

*** purpose

    what is the purpose of this final exam and how does this inform the writing. conclusions aren't worthy very many points.
*** audience
** common errors

- taking sides and forgetting about the counterarguments.
- too much law/too little analysis
- failing to note the relationship between the issues
- irrelevant legal principles

shea specific:
- never have to repeat a rule. true across questions: q1 v q4, etc. but not required
- can use abbreviations so long as understand what the abbreviations are: ie, K.
** how score

- all start with 0 and earn points up to 100.
- most points for analysis
  - has rule chart and analysis chart and
- checklist
- no subtraction unless you fail to follow directions.
** types of answers
- givens : no analaysis: acknowledge and move on
- gimmes: analysis short because element is met, but not given; no reasonable counter arguments
- fighting issues: analysis is in depth; there are reasonable arguments on both sides or defenses that have to be considered

*** conclusions of law or fact expressly stated

    should not do analysis.
