* Formation
** mutual assent
** objective theory of assent
** preliminary negotiations
** offer
** acceptance
** revocation
** rejection
** counter offer
* interpretation
** interpreting terms
** gap filling
** form k's which terms were agreed to
** battle of the forms
** parol evidence rule
** mistake in integration
* enforcement
** consideration
A contract is an enforceable promise. With some exceptions, to be enforceable a promise must be supported by a consideratoin. A promise is supported by a consideration if it is bargained for. A promise is bargained for "if it is sought in exchange for his promise and is given by the promisee in exchange for that promise."
** modification & preexisting duty
** promissory estoppel
** statute of frauds
** implied duty of good faith (multiple choice only)
** warranties (multiple choice only)
* defenses
** incapacity
** undue influence
** misrepresentation
** unconscionability
** public policy/illegality
** mistake
'a belief that is not in accord with the facts"
** impracticability / impossibility
impossibility: impossible due to no fault. impossible on behalf of the side claiming the defense
impracticability: "extreme and unreasonable difficulty"
** frustration of purpsoe
principal purpose substantially frustrated without his fault by occurrence/non-occurence that was a basic assumption
* damages
** expectation
** reliance
** restitution
** limitations on damages
** equitable damages: specific performance, injunctions
