#+OPTIONS: toc:2
* COMMENT readings
  Tuesday: finish up this week's readings -- pages 335-349, 352-353;
  Start in interpretation -- pages 359-361; 370-384 (skim pages 361-370)

  If we get through all of that on Tuesday, Thursday's readings will be:
  Filling in the Gaps -- pages 384-398 [skim 398-407]
  Form Ks -- pages 408-417

* chapter 5 discerning the agreement

  Once it is concluded that there has been mutual assent to a contract, there remains the task of ascertaining the terms that will bind the parties

1. interpreting the meaning of the words
2. gap-filling when a situatoin arises that is not explicitly handled by the terms of the parties' agreement.
3. identifying which term is adopted by the parties when, though it is clear the parties intended to enter into contractual relations, the terms of the offer differ from the terms of the acceptance.


* interpreting the meaning of the terms

  language deficienies:

1. ambiguous, terms that have more than one meaning
2. vagueness, when the question is whether the term was meant to apply beyond its clear core meaning


courts have developed an objective theory with a subjective twist.

** ambiguous terms

*** COMMENT purpose

consider the problem of "misunderstanding" which can occur when words have more than one meaning and a question arises to which, if any, was the meaning agreed to by both parties.

bear in mind, is it objective or subjective?

*** raffles v wichelhaus

court of exchequer, 1864

**** Procedural History

***** facts

      Defendant purchases cotton from Plaintiff to ship from India on a ship named Peerless. A ship arrives which sailed in October with no cotton. A ship arrives which sailed in December with Cotton, but Defendant refuses to purchase. Sue for breach of contract.

***** lower court

      The lower court ruled in favor of the Plaintiffs holding essentially that the shipping date was not specified and /whihc/ peerless by which it arrived was not an essential term of the K.

**** Questions Presented

     Was there a K formed when the buyers meant one ship Peerless but the sellers meant another?

**** Rule

     There must be consensus on the meanings of the terms in a K. Here there was evidence introduced that the parties did not and thus not K.

**** Reasoning

     Since the term was ambiguous and the parties had differing meanings attached to the term, there was never a K in the first place and thus the Defendants must prevail.

**** Holding

     Overruling the lower court, this court ruled that there was no K formed. However, there have been several criticisms. The court never took an objective standard but a subjective one. Was there a reason that the Defendant knew of another Peerless such that he would have an expectation to /which/ ship he was obligated?

**** Main Takeaway

     What is an objective standard for judging interpretation? And how much subjectivity should come in? Here was there an objective reason for a misundertanding? would an average cotton merchant know about the two peerless ships? Was the ship a material term or an incidental one? Is it important that the parties were allowed evidence to show they disagreed? Is it enough on the face of the K that they did not disagree?


*** oswald v allen

**** Procedural History

***** facts

      Oswald, Plantiff, offered to purchase the swiss coins from Defendant. The woman had offered her swiss collection for sale, but this did not include swiss coins in her rare coins collection. The plantiff did not speak good english and went through his brother. A deal was struck but later Allen wanted to back out after her children expressed sentimental interest.

***** lower court

      The lower court ruled that a K did not exist thus ruling for the defendant.

**** Questions Presented

     Does a contract exist when the two parties materially differ about term(s) of the K

**** Rule

     when any of the terms used to express an agreement is ambivalent, and the parties understand it in different ways, there cannot be a contract unless one of them should have been aware of the other's understanding.

**** Reasoning

     there is no sensible way of choosing which terms to legally enforce so the agreement is a nullity

**** Holding

     there was no contract as the parties never had the "one mind" that was required.

**** Main Takeaway

     the contract was ambiguous, not vague, and neither was aware of the overloaded term on the other's view. in this case the K is voided. However, had one of the arties known of the confusion on the other side the result could be different.


** vauge terms
*** weinberg v edelstein

    supreme court, new york county 1952

**** Procedural History

***** facts

      The Plaintiff brings suit for violation of a restrictive covenant on his lease. The plaintiff's lease prevents the selling of dresses by other lease holders. The defendant recently moved in and sell swomen's clothes, including two piece outfits of blouses and skirts. The question before the court is are these ensembles dresses or can they be?

***** lower court

      I think this is actually the trial court in this instance. the supreme court of NY is not the final court which goes by the name court of appeals.

**** Questions Presented

     When a term is vague, how does the court resolve the term toa specific meaning for enforcement.

**** Rule

     the judge consults the dictionary, industry terms, industry norms like manufacturing unions, and finally consults trends in the industry. once at some point with a plan, he interprets the terms in the covenant so as to protect both parties.

**** Reasoning

     the court recognized both the power of the covenant as well as the right of the defendant to merchant items outside of that covenant. finding no solution in the dictionary, trade unions, he turns to customs. the important part is that "dress" is in the process of becoming even more vague and it was on the plaintiff to express the restrictions more clearly on the defendant. absent this he gets a conservative defintion of dress for the purposes of his covenant.

**** Holding

     The trend has been for two pieces to be worn as dresses and not. Seeing as the contract for the defendants was just recently written, the plaintiff had the opportunity to clarify dress or introduce restrictions on the D to reflect the evolving play between dress versus blouse and skirt combo. Barring this, the court is reluctant to impose restrictions on defendant not in a strict construction. The defendant must not sell the two pieces as a single unit and cannot compel the purchase of one side with the other. But otherwise dress is read to be the single piece.

**** Main Takeaway



*** frigaliment importing co v bns international sales

    US District Court, Southern District of NY, 1960

**** Procedural History

***** facts

      Defendant entered an agreement to provide chicken to Plaintiff. Specifying USDA grade A chicken, specified weights. The industry on the retail side uses chicken to indicate broilers and fryers and reseves the term fowl for the older chickens more suitale for stewing. The defendant was a newcomer to the industry and not aware of this customary usage in the industry. However, NY law requires a showing that this use is "so long continuance, so well established, so notorious, so universal and so reasonable in itself, as that the presumption is violent that the parties contracted with reference to it, and made it a part of their agreement". This show failed as while understood on the consumption of bird side, the processing side had no use of this grading and did not rely on it.

      Defendant provided older chickens to satisfy the heaving category of birds in the contract. Plaintiff protested but accepted the first shipment. Further they greenlit the second shipment of birds without clarifying. Plaintiff brings this action for breach.

***** lower court

      this is the trial court

**** Questions Presented

     Is a stewing chicken a chicken as used in the contract between the parties?

     How does one resolve a vague term in a contract?

**** Rule

     The answer to the latter question informs how to answer the former. The court probes the industry to find out what is meant by chicken. They find there are two permeating definitions and the indsutry recognizes it can be kinda overloaded and seeks to minimize which concept is used. Recognizing that a contract is the the agreement of "two sets of external signs", a subjective standard can come in when a defendant uses one of the recognized meanings. It is on the plaintiff to demonstrate that different meaning was meant in the contract, a barrier they failed to overcome.

**** Reasoning

     Industry practices differ. The cost of the birds was priced below the going rate for younger birds. the defendant was a newcomer to the industry and usage of "chicken" as the broilers is not so pervasive as to attach meaning.

**** Holding

     The plaintiffs have failed ot persuade the court that their interpretation of chicken is controlling. The defendant believed they could satisfy the contract under their notion of chicken and its not clear why this was not controlling.

**** Main Takeaway

     When the terms are vague, follow several steps to resolve. dictionary, common usage, terms of the contract itself, context of the dealings, and then finally burden of proof

** filling in the gaps

   interpreting terms that are present and supplying terms when contracts are silent on a particular issue. when filling gaps, difference between implied-in-fact and implied-in-law.

*** intro

**** implied-in-fact

     "those that the parties actually, albeit implicitly, have agreed to

**** implied-in-law

     thought to be imposed on parties without their consent. default rules and immunitable rules. default rules refer to those legal rules that the parties can avoid or vary by means of an express clause that differs from the term a court will otherwise supply by default. immutable rules, by contrast, may not be varied by consent and will override any express clause to the contrary.

**** further considerations

1) need to decide if there is sufficient manifestation of assent to conclude that a legally enforceable contract exists
2) how to interpret the assent that has been manifeted.

**** illusory promises

     "is a promise "illusory" because it leaves complete discretion to perform or not in the hands of the purported promisor. i neach of these cases, the court fills this gapin the manifetation of assent by supply an obligation to exercise this discretion in "good faith". here we are concerned only with how and why the court fills the gap, in constrast with sun printing, where it refused to do so" p. 392

*** Sun Printing & Publishing Ass'n v. Remington Paper

    court of appeals of new york 1923

**** Procedural History

***** facts

      Plaintiff agreed to buy and defendant to sell 1,000 ton of paper per month. The price and duration would be negotiated on an ongoing basis to be capped by the price charged by the Canadian Export Paper Compnay to large customers. The contract failed to anticipate what happens when no agreement is made (invoking the capped price) and then the rate the Canadian Export Paper Company fluctuates during this time. Must the agreement be restarted or the Plaintiff's price fluctuate accordingly? And this is when there were no agreed upon terms.

***** lower court

      Super hard to follow: Action by Sun Printing & Publishing Association against the Remington Paper & Power Company, Inc. From an order of the Appellate Division . . . which reversed an order of the Special Term denying plaintiff’s motion for judgment on the pleadings, and granted said motion, defendant, by permission, appeals.

      Defendant Remington is appealing a motion for judgment on the pleadings on the following certified question, "does the complaint state facts sufficient to constitute a cause of action?" Defendants are questioning the underlying contract at all rather than even an argument about its interpretation.

**** Questions Presented

     When a K is missing terms, how do we determine whether to abandon the K or conjure terms?

**** Rule

     The contract lacked key operative terms and the court should not read them in.

**** Reasoning

     The K required price and duration of that price to be negotiated. When the defendants stated their intention not to negotiate, this necessarilly left the durations unspecified. This causes problems as how long does the capped price last? Does the Plaintiff get to continue at the maximum price until he feels like changing when a new maximum price is in his favor? Were it 12 option contracts, the purchaser would have a one way ratchet to continue under the current option and only exercising the option when it was in his favor. There was an agreement to agree on the term, something from which the defendant can walk away from.

     As to whether it is on the court to repair the K into a state to keep it functional:
     "there is need, it is true, of no high degree of ingenuity to show how the parties, with little change of language, coudl have framed a form of contract to which obligation would attach. the difficulty is that they framed another. we are not at liberty to revise while professing to construe".

**** Holding

     The K contained agreements to agree to terms after the first few months. This provides the ability for D to walk away, which it did.

**** Main Takeaway

     It is not for the courts to repair but to construe. Cardozo sets a high bar for what the court can impose into a contract. "no high degree of ingenuity" was required in this case but they refrained.

*** New york central iron works co v united states radioator co

    court of appeals of new york 1903

**** Procedural History

***** facts

      Plaintiff secured a contract from Defendant for radiators for "their entire radiator needs for the year 1899". After the K formation, iron prices rose but the K price remained the same. Plaintiffs were able to undercut the market and their order volume went up quite a bit. Defendant claims that there was a mutual mistake in framing the K, since the intention was to limit the quantity of goods to be delivered to an amount such as had been called for in previous years of similar dealings between the parties.

***** lower court

      lower court ruled for plaintiffs, rejecting the argument limiting the contract to the volume of goods sold in previous years.

**** Questions Presented

     Can a contract have terms introduced by a court to limit exposure when a commodity underlying has increased in value?

**** Rule

     Actors in a K have a responsibility to act responsibly and reasonably towards each other.

**** Reasoning

     The contract is open to good faith ordering. The K may be used for purposes contemplated by it, but not more. speculation was not within the purposes of the agreement, and had the defendants offered evidence of it, they could have prevailed.

**** Holding

     There was no evidence that the Plaintiffs had acted unreasonably or irresponsibly. As such, the lower court ruling in favor of plaintiffs was upheld.

**** Main Takeaway

     Actors in a K have a duty to behave reasonably and responsibly towards each other. this is not to say that benefits can be reaped, but the pursuit of these unforseen benefits much stay within the bounds of the original K. The court is willing to read a limit onto the commodity amount, but not to the degree requested--the same as previous years before the price spike--but a reasonable amount tied to the plaintiff's reasonable needs. It was difficult to separate increase in business due to price hike versus speculation in the iron market.

*** Eastern Air Line, Inc, v. Gulf Oil corp

    US District Court, Souther District of Florida, 1975

**** Procedural History

***** facts

      Gulf tried to back out of its contract to supply jet fuel to Eastern airline. Presumably this arises during the oil embargo when gas prices have risen steeply. Gulf argues that this is not a binding requirements contract, was void for want of mutuality, and was "commercially impracticable".

***** lower court

      this is the court of first instance

**** Questions Presented

     Does a requirements contract contain enough certainty to be considered a legally enforceable contract?

**** Rule

     Requirements contracts are specifically recognized

**** Reasoning

     Requirements contracts were found invalid previously but the UCC had recently been adopted and provided for them. They required an operating business which provided an expectation of quantity, rounding out the lacking concrete terms previously missing. There was mutuality and definiteness bound by the estimated amount of commerce.

**** Holding

     The requirements contract is legally enforceable.

**** Main Takeaway

     I'm not too sure. It seems striaghtforward out of the UCC. this isn't even an evolving standard of common law like IIED or the like, its statutory language. The opinion never touches on the commercial impracticable complaint so presumably that would be the main takeaway? I'm sorry the iranians ruined the oil market but you have 6 more years on your contract? But this should play a larger part in the opinion if so.

*** wood v lucy, lady duff-gordon

    court of appeals of NY, 1917

**** Procedural History

***** facts

      Plaintiff was a socialite with an un-monetized fashion influence. She contracted with Defendant to monetize this influence and share half of the profits. Some way through, Defendant endorsed fabrics without the knowledge of the Defendant, who was promised exclusive use of her influence. Plaintiff sued for breach and Defendant argues no K as there is no duty imposed on Plaintiff.

***** lower court

      A lower court denied a motion by defendant for judgment in her favor which was reversed by the appelate court. This is an opinion about that judgment for the defendant in the final court of NY.

**** Questions Presented

     Under an exclusive licensing agreement, is there an implied duty on the license executor?

**** Rule

     When promises are otherwise useless, an obligation to pursue them can is implied in the contract. But these promises that would otherwise be useless have value in "enforc[ing] the conclusion that the plaintiff /had/ some duties".

**** Reasoning

     The Plaintiff had two promises that were utterly worthless without action on his part: giving half of the profits and a monthly accounting of the money. Without an implied duty on his half these would mean nothing.

**** Holding

     The promises to share the profits and monthly accounting was an implicit promise to undertake actions to generate these revenues. There was binding promise on the side of the Plaintiff and therefore there was no missing element from K formation.

**** Main Takeaway


* identifying the terms of the agreement

** form contracts or "contracts of adhesion"

*** intro

    challenge our notion of assent: written by one of the parties and generally unread by the other. "when the form ued by one party conflicts with the form used by the other, we are faced with the problem of identifying which terms govern"

*** carnival cruise lines v shute

    supreme court 1991, Justice Blackmun

**** Procedural History

***** facts

      The plaintiffs booked passage on a cruise ship leaving LA and traveling to mexico from the state of Washington. While in international waters, the plaintiff slipped and injured herself on a guided tour of the kitchen. She brought suit in federal district court in Washington, contrary to a forum selection clause stipulating all litigation must occur in Florida. This action is whether the forum selection clause is enforceable, and the suit therefore moot.

***** lower court

      The district court dismissed for lack of jurisdiction since the ties to the state of washingotn were insubstantial. the 9th circuit refused to enforce the forum selection clause and carnival cruise lines appeals.

**** Questions Presented

     Are non-negotiated forum-selection clauses legally enforceable when the plaintiff has had notice?

**** Rule

     The non-negotiated aspect is immaterial if the terms are reasonable and are subject to fundamental fairness scrutiny.

**** Reasoning

     The forum selection clause is valid. Just because it is non-negotiated does not invalidate it. There are good reasons for it and the customer benefits from reduced fares for its good reasons. The selection does not violate a fundamental fairness; the cruise operates frequently and is based in florida. further, respondents note they were on notice of the clause.

**** Holding

     the forum selection clause was reasonable and therefore valid. It was reasonable for several reasons, including benefits accruing to the plaintiffs.

**** dissent from stevens

     notes that the terms are tiny, in response to the court's highlighting of the operative clause. the terms come /after/ purchase and receipt of the ticket. the ticket also includes a limiting refund clause, and thus the average consumer would risk having to sue in Florida rather than lose the value of their ticket without a refund. This choice does not render the forum choice as reasonable.

     this and similar mechanisms all allow for slight tipping of the scales of justice, which can cumulatively add up. there are two strands of traditional contract reasoning that both argue against the result of the court. traditionally, hightened scrutiny is placed on form contracts with no negotiation with a large discrepancy of bargaining power. further, some question if there can be a contract at all as there is no "manifesting knowledge and voluntary consent". The second strand of traditional contract theory objects to the forum selection as against public policy. forum selection can be invalidated if not bargained for, creates additional expense for one party, or denies one party a remedy.

**** Main Takeaway


*** caspi v microsoft network

superior court of NJ, appellate division, 1999

**** Procedural History

***** facts

***** lower court

      Ruled in favor of microsoft that its forum selection clause stipulating washington courts is valid

**** Questions Presented

     Are non-negotiated forum-selection clauses legally enforceable when the plaintiff has not necessarily notice?

**** Rule

     The clause is binding.

**** Reasoning

     Shute is nearly dispositive except that the plaintiff's did not stipulate to have read the terms. However, the plaintiff's had ample notice and time to read. the terms were not hidden, followed the standard format and were reasonable.

**** Holding

     The contract is binding and the NJ court lacks jurisdiction.

**** Main Takeaway

* which terms were agreed to?

** intro

   when terms of acceptance are different from the offer, what is binding? we know the parties intended to contract, we are faced with figuring out which terms to which they agreed when "their manifestations of assent conflict". "battle of the forms" as it often arises as a result of conflicting writings

** step-saver data systems, inc, v wyse technology

us court of appeals 3rd circuit 1991

*** Procedural History

**** facts

     step saver builds computers and installs software. one suite performed poorly leaving returned computers and lawsuits. step-saver sues vendors for breach of warranty and lack of merchantability of software. the box top contained a clause stipulating by opening the software you agreed that there was no implied merchantability and that those terms were final and included all relevant terms.

**** lower court

     reverse lower court which held that

*** Questions Presented

    Do "box top" terms govern an agreement to purchase software following a phone call stipulating items and purchase price or do they constitute a counter offer after the intial contract?

*** Rule

*** Reasoning

    The box-top attached substantially different terms after a contract had been made. as such, under ucc, doesn't hold weight. wasn't indefinite, as UCC allows for some play.

**** indefinite

     debate about sale of software versus sale of license. court argues that rights are largely the same, can figure out later. but court notes the following were discussed and agreed to 1) specific goods 2) quanitty 3) price. argue that warranty discussion was not involved but ucc grants warranty unless specifically declaimed, and therefore we have software with a warranty. so it is definite enough without box top

**** counter offer

     argues a conditional counter offer, which step-saver accepts by opening and not returning the software. court is not sure that conditional acceptance applies when a contract has partial performance (implying that partial performance under the original terms doesn't allow for the retraction or perhaps that the original terms are binding as they were).

     analyze a few tests, and then settle on a test for what is a conditional acceptance: "requires the offeree to demonstrate an unwillingness to proceed with the transaction unless the additional or different terms are included in teh contract". you have to die on this hill or else it just goes in the battle of the forms.

     says the language on the box top isn't forceful enough. "consent by opening" ... "provides no real indication that the party is willing to forego the transaction if the additional language is not included in the contract". note that there was an offer to get a refund but not enough in this case as not clear that tsl was willing to forego the sale if not accepted.

     wow, testimony from head of step saver that tsl told him that the box top didn't apply to him since he was not an end user but middle man. step saver was asked to sign documents formalizing the box top agreement, refused to do so, but trade still continued. also, box top prevents transfer of license, but both parties agree this term isn't binding on them. willing to proceed with violation of one term, and why is one non-negotiable but the other isn't?

*** Holding

    rejects lower court dismissing of claims against tsl and remands for consideration.

*** Main Takeaway

    Big difference between CL and UCC: last shot rule. send an offer, change one of the terms, send it back, considered a counter offer. if someone proceeds with contract despite different terms of a "supposed acceptance", 'he woudl, by his performance, constructively accept the terms of the 'counteroffer'', and be bound by its terms'. last-shot rule. UCC in 2-207 rejects this. remove the power of the last shot rule from the seller. hold only the terms that both parties have agreed to.

    material alteration. when are these acceptable and under what conditions?

** union carbide corp v oscar mayer foods corp

   7th circuit court of appeals Posner

*** Procedural History

**** facts

     Union carbide sold sausage casings from chicago subject to a 2% sales tax. it noticed a competitor sending from outside the city and eliding the taxes, so it had oscar mayer address invoices to an office outside of chicago and stopped sending the tax on the invoices. 8 years later gets popped for 150k in back taxes and penalties, and points to tax indemnification language on the back of invoices

**** lower court

     summary judgment for oscar mayer

*** Questions Presented

    Does the tax indemnification language put the tax burden on oscar mayer?

    Was there material breach for not paying the taxes?

*** Rule

    The tax indemnification is against assessed taxes, not an open ended liability. In the alternative, the inclusion on the back of the invoice would be a material change no assented to by Oscar Mayer.

    posner then goes into detail about how to determine if this new clause is to be read into the contract:

    #+BEGIN_QUOTE

    To summarize, a term inserted by the offeree is ineffectual (1) if the offer expressly limits acceptance to the terms of the offer, or (2) if the new term (a) makes a material alteration, in the sense that consent to it cannot be presumed, and (b) there is no showing that the offeror in fact consented to the alteration—whether (i) expressly, or (ii) by silence against the background of a course of dealings.

    #+END_QUOTE

*** Reasoning

*** Holding

*** Main Takeaway

** ProCd v Zeinberg

*** Procedural History

**** facts

**** lower court

*** Questions Presented

*** Rule

*** Reasoning

*** Holding

*** Main Takeaway
