#+OPTIONS: toc:2
* Reaching an Agreement

  formation of a contract requires two basic elements
1. the mutual assent of the prties
2. and some showing that this assent is the _kind_ that the law will enforce.

distinguish subjective v obective conceptions of assent. but objective approach contains a subjective approach as well.

* Objective theory of assent

** naive view

*** meeting of the minds Dickinson v Dodds:

    "it must, to constitute a contract, appear that the two minds were at one at the same moment of time ..." and that "the existence of the same mind between two parties is essential in point of law to the making of an agreement". often referred to as "meeting of the minds".

    thoughts to be aware of: objective theory of assent at contract formation vs contract interpretation

** Embry v Hargadine, McKittrick Dry Goods Co

   St. Louis Court of Appeals, 1907

*** Procedural History

    Lower trial court gave jury instructions requiring intent in contract formation, Plaintiff appeals as this requirement was not required as a matter of law.

*** Questions Presented

**** Facts

     Contract salesman pesters boss for contract renewal 7 days before contract expires at the end of the year or else he will leave immediately. Dispute of whether boss intimated that "go ahead, you're all right" or if it was a dismissive conversation.

**** jury instruction requested

     Apellant requested jury instruction of that his version of the facts constituted a contract between the parties and if found to be true would be entitled to the contracted upon $2000 salary.

**** jury instruction given

     if you (the jury) find both parties thereby _intended_ and did contract with each other for plaintiff's employment for one year from and including December 23, 1903, at a salary of $2000 per annum

**** Question

     Appellant states it was error to require for finding for plaintiff, find not only that the conversation happened in the way alleged but that "both parties intended by such conversation to contract with each other".

     "whether the formation of a contract ... depended on the intention of both Embry and McKittrick. Did what was said constitute a contract of re-employment on the previous terms irrespective of the intention or purpose of McKittrick?"

*** Rule

    General rule is that "to constitute a contract there must be a meeting of the minds of the parties and both must agree to the same thing in the same sense". But there are exceptions. "The inner intentions of parties to a conversatoin subsequently alleged to create a contract, cannot either make a contract of what transpired or prevent one from arising, if the words used were sufficient to constitute a contract."

    Intention matters, but only the intention "words or acts indicate; not one secretly cherished which is inconsistent with those words or acts."

    "The law imputes to a person an intention corresponding to the reasonable meaning of his words and acts. It judges his intention by his outward expressoins and excludes all questions in regard to his unexpressed intention."

*** Reasoning

**** Can it be a contract

      Taking these exceptions to the "meeting of the minds" rule, its possible that McKittrick may not have intended to employ Embry but it would have been "taken by a reasonable man to be an employment, and Embry so understood it, it consttuted a valid contract of employment for the ensuing year"

      so two parts?
1. a reasonable person would have understand the (publicly viewable) intention to form a contract
2. Embry did so understand

**** Was the language of this character

     When written, straight question of law and a court may decide or when unambiguous oral words. If disputed the question is for the jury

*** Holding

    Reversed to put forth Embry's jury instruction to the jury. "No reasonable man would construe that answer to Embry's demand that he be employed for another year, otherwise than as an assent to the demand, and that Embry had the right to rely on it a an assent."

    The contract formation does not require the secret intentions but the visible intentions gleaned from words and actions; Embry's version of the facts, if true, would as a matter of law constitute a contract

*** Main Takeaway

** Lucy v Zehmer

   Supreme Court of Appeals of VA 1954

*** Procedural History

**** facts

      Zehmer wife and husband write contract to Lucys for sale of their farm for 50k. Argue they thought the offer was in jest and had several drinks. Got his wife to sign the document but did not "deliver the memorandum to Lucy, but that Lucy picked it up, read it, put it in his pocket, attempted to offer Zehmer $5 to bind the bargain, which Zehmer refused to accept". At this point, Zehmer realized that Lucy was serious and reassured him he had no intention to sell and thought the matter a joke.

      Terribly confusing narratives but seem consistent that
- something was written stating "I" intend to sell
- was redrafted to include "We" intend to sell to include the wife
- included provision that title satisfaction was part of deal
- there was alcohol involved
- there was some joking. Zehmer says about the whole thing, Lucy understood about payment of 50k that night

**** previous ruling

     Held that Lucys had "failed to establish their right to specific performance" and dismissed the bill.

**** contract?

     My thoughts

     The is an equitable solution which doesn't mean that the contract wasn't formed. Perhaps the court thought that there were other remedies available?

*** Questions Presented

    Does Zehmer's contention that he never intended a real contract negate the whole thing?

*** Rule

    "we must look to the outward expression of a person as manifesting his intention rather than to his secreat and unexpressed intention"

*** Reasoning

**** drunk?

     He drove home that night and testified that he was not too drunk to execute a binding agreement.

**** not earnest?

     Did not let the Lucys in on the joke until after they had done title research and were prepared to execute the contract. "Had argued about it, discusssed its terms, as Zehmer admitted, for a long time. Lucy testified that if there was any jesting it was about paying 50k that night. the contract and evidence show that he was not expected to pay the money that night. ... In any event there had been what appeared to be a good faith offer and good faither acceptance, followed by the execution and apparent delivery of a written contract" ... "Not until then, even under the defendant's evidence, was anythign said or done to indicate that the matter was a joke." He wishpered to his wife that it was a joke specifically so that the Lucys would not be able to hear it.

**** mental assent

     "if the words or other acts of one of the parties have but one reasonable meaning, his undisclosed intention is immaterial except when an unreasonable meaning which he attaches to his manifestations is known to the other party".  Private intentions aren't relevant unless the other person understands those intentions.

     "So a person cannot set u that he was merely jesting when his conduct and words would warrant a reasonable person i nbelieving that he intended a real agreement".

*** Holding

    "Whether the writing signed by the defendants and now sought to be enforced by the complainants was the result of a serious offer by Lucy and a serious acceptance by the defendants, or was a serious offer by Lucy and an acceptance in secret jest by the defendants, in either event it constituted a binding contract of sale between the parties."

    Reversed and remanded for entry of t

*** Main Takeaway

** (Restatement of Contracts)

*** Requirement of a bargain
    formation of a contract requires a bargain in which there is manifestation of mutual assent to the exchange and a consideration

*** Manifestation of mutual assent

    manifestation of mutual assent to an exchange requires that each party either make a promise or begin or render a performance.

*** conduct as manifestation of assent

1. the manifestation of assent may be made wholly or partly by written or spoken words or by other acts or by failure to act
2. the conduct of a party is not effective as a manifestation of his assent unless he intends to engage in teh conduct and knows or has reason to know that hte other party may infer from his conduct that he assents.
3. the conduct of a party may manifest assent even though he does not in fact assent. In such cases a resulting contract may be voidable because of fraud, duress, mistake, or other invalidating cause.

** What is an offer

   traditional mutual assent manifests in offer and acceptance. However, in complex commercial transactions it can be difficult to separate parties into offeror and offeree. Various doctrines allow interpretation of complex situtation in the traditional guise of offer and acceptances.

   offer defined in restatement as "manifestation of willingness to enter into a bargain, so made as to justify another person in undestanding that his assent to that bargain is invited and will conclude it."

   in following cases, "the allgeded offeror claims that the other party was not justified 'in understanding that his assent to that bargain is invited and will conclude it'".

** Nebraska seed co v harsh

   Supreme Court of Nebraska, 1915

*** Procedural History

**** facts

     Harsh, a farmer, sends letter (telegram?) stating rough quantity and price sought "I want 2.25 per cwt. for this seed". Nebraska seed company immediately telegraphs "accept your offer.... wire how soon can load". Then sends letter confirming and offering shipping instructions. Farmer does not deliver seed.

**** previous court ruling

     "trial to a jury, verdict and judgment for plaintiff, defendant appeals"

*** Questions Presented

    Does the letter from the farmer constitute an offer "so made as to justify another person in understanding that his assent to that bargain is invited and will conclude it"?

*** Rule

    A request for bids does not constitute an offer

*** Reasoning

- no explicit use of "I offer to you" but general language as in an advertisement "addressed generally to those engaged in teh seed business, and is not an offer by which he may be bound, if accepted, by any or all of the persons addresse". 'invitations to trade ... such inquiries may lead to bargains, but do not make them'
- did not fix time of delivery, "and this seems to have been regarded as one of the essentials by plaintiff"
  - does this matter? seems like some final technicalities can be worked out after a principal agreement... can you not shake hands on an agreement and then figure out details after binding?
- "offer" lacked specificity as to the exact amount of grain to be sold. "we may assume that when he wrote the letter he did not contemplate the sale of more seed than he had"
- practicality concerns: if this was binding and he sent advertisements to multiple seed buyers "would subject him to a suit by each one receiving a letter, or invitatoins to id, even though his supply of seed were exhausted.
  - seems like the strongest argument
  - Quoted from MA Supreme Court: "Care should always be taken not to construe as an agreement letters which the parties intended only as a preleminary negotiation".

*** Holding

    "In our opinion, the letter of D cannot be failrly construed into an offer to sell to the plaintiff".

*** Main Takeaway

** lefkowitz v great minneapolis surplus store, include

   SC Minnesota 1957

*** Procedural History

*** facts

    Store puts two advertisements in successive weeks advertising fur coats worth "to 100" for $1, first come first served. the second week "black lapin .. worth 139.50 ... $1" (elipses in the original). Lefkowitz ensured he was the first person in line after the first week and was told it was for women only as "house rules". on the second visit was told he was aware of the house rules.

*** previous court ruling

    "Appeal from an order of the Municipal Court f Minneapolis denying the motion of the D fr amended findings of fact, or, in the alternative, a new trial. the order for judgment awarded the plaintiff the sum of $138.50 as damages for breach of contract"

    previous court gave him value of the black lapin since its value was known and not a general estimate, minus his $1 consideration.

*** Questions Presented

    "We are concerened with whethe the advertisement constituted an offer, and, if so, whether the plaintiff's conduct constituted an acceptance".

*** Rule

    "The test of whether a binding obligatoin may originate in adversitements addresse to the general public is 'whether the facts show that some performance was promised in positive terms in return for something requested' (secondary source)".

    "when the offer is clear, definite, and explicit, and leaves nothing open for negotiation, it constitues an offer, acceptance of which will complete the contract".

*** Reasoning

**** Was it an offer

     "The facts before us that the offer by the defendant of the sale of the lapin fur was clear, definite, and explicit, and left nothing open for negotiation." P was first in line and brought the amount requested so now he is "entitled to the performance on the part of the D"

**** Can it be modified (house rules)

     "advertisement had no such restriction. the objection may be disposed of brifly by stating that, while an advertiser has the right at any time before acceptance to modify his offer, he does not have the right, after acceptance, to impose new or arbitrary conditions not contained in the published offer"

*** Holding

    The lower court was correct

*** Main Takeaway

** Leonard v Pepsico

   US District Court, Southern district o new york 1999

*** Procedural History

**** facts

     Pepsi ran a contest which included a top prize of a harrier jet. Plaintiff raised money to buy pepsi points and submitted a check along with 15 pepsi points for his harrier jet.

*** Questions Presented

    Whether the offer was serious

*** Rule

    "the court must not consider defendant's subjective intent in making the commercial, or plaintiff's subjective view of what the commercial offered, but what an objective, reasonable person would have understood the commercial to convey"

    "a basic rule of contracts holds that whether an offer hsa been made depends on the objective resaonableness of the allgeded offeree's belief that he advertisement or solicitation was intended as an offer".

*** Reasoning

**** for the rule
     the reasoning behind the rule is that it must be an expression of will or intention ... it is on this ground that we must exclude invitations to deal or acts of mere preliminary negotiation, and acts evidently done in jest or without intent to create legal relations.

**** application of the rule

     "Plaintiff's insistence that the commercial appears to be a serious offer requires the Court to explain why the commercial is funny. Explaining why a joke is funny is a daunting task; as the essayist E. B. White has remarked, 'Humor can be dissected, as a frog can, but the thing dies in the process...'" "zany humor".

*** Holding

    Pepsi gets summary judgment

*** Main Takeaway

** Preliminary Negotiations
*** empro manufacturing co v ball-co manufacturing

    US Court of Appeals, 7th Circuit 1989

**** Procedural History

***** facts

      Ball-co floated its assets and Empro took interest to purchase the company. They signed a letter of intent to proceed, which contained provisions for Empro to back out. Ball-co started negotiating with someone else leading Empro to file suit in diversity to get a temporary restraining order. District judge read the letter of intent and dismissed under 12(b)(6) for failure to state a claim. The evidence there was that the agreement contained "subject to" twice so that the letter of intent was "subject to" "the execution of a definitive contract" and the letter of intent had no "independent force".

**** Questions Presented

     Does the letter of intent bind the the companies?

**** Rule

     "Contract law gives effects to the parties' wishes, but they must express these openly. Put differeenty, 'intent' in contract law is objective rather than subjective -- a point Interway makes by holding that as a matter of law parties who make their pact 'subject to' a later definitive agreement have manifested an (objective) intent not to be bound...".

**** Reasoning

- the subject to is informative but not dispositive.
- the text of the letter was "general terms and conditions" indicating that revisions and changes were forthcoming; empro also endeavored to ensure that it could walk away from the deal, lending credence to the fact that the letter created no obligations.
- but there seemed to be no language making it an option contract which would bind Ball-co and give Empro choice. In agreeing to the letter, Ball-co indicated that "some clarifications are needed" indicating it intended to change the agreement.
- Illinois law allows companies to proceed in stages to agreement. Making the early stages binding would ruin this practice

**** Holding

Empro may have had the intention to form an offer with this but the intention was obvious to the objective standard. Illinois allows for negotiations leading up to a final agreement.

**** Main Takeaway
     if there is no clear acceptance it can't even be close
*** arnold palmer golf co v guque industries

    united states court of appeals, 6th circuit 1976

**** Procedural History

***** facts

      arnold palmer company wanted to inhouse its manufacturing, so set out to trade 25% of its stock to a company in exchange for a manufacturing subisidiary. A "Memorandum of Intent" was finalized laying out the general terms and going into quite a bit of detail. It had a section maintaining that lawyers were responsible for forming a contract.

***** lower court

      Held that this draft was indeed not a binding contract because it provided evidence of the parties not to be contractually bound. the case was granted summary judgment.

      came to the court on a fact issue. (summary judgment) a question of fact.

**** Questions Presented

     How does a court determine whether the intent was present between two parties to form a contract in a memorandum of intent.

**** Rule



**** Reasoning

     Luckily, the court did not have to. They find that there is a plausible reading both ways. This could be the agreement and intent from both sides with instructions to memorialize it, or this could be a letter stating where they are now and the lawyers must finish it. As such, summary judgment is an inappropriate tool as the settling of this is not a matter of law but a matter of fact.

**** Holding

     "Considering this appeal in the light of these authorities, we determine that our proper course is to remand this case to the district court for tiral because we believe that the issue of the parties' intention to be bound is a proper one for resolution by the trier of fact."

**** Main Takeaway

     Mutual assent is not necessarily a matter of law. The UCC and restatement necessarily fall back to notions of understanding and generalities.

     "a contract for sale of goods may be made in any manner sufficient to show agreement, including conduct by both parties which recognizes the existence of such a contract"

     "an offer is the manifestation of willingness to enter into a bargain, so made as to justify another person in understandin that his assent to that bargin is invited and will conclude it".

*** Copeland v Baskin Robbins usa
    Court of Appeal, Second District, Division 7 California 2002

**** Procedural History

***** facts

      Copeland wants to purchase an ice cream plant that Baskin Robbins is shutting down but only on the condition that BR agrees to buy ice cream from him for 3 years. They agree and negotiate and lay out a lot of legwork along with a leeter stating this is their intention but stating there are more details to be worked out. After some time BR decides the ice cream purchasing plan is not in its interests and breaks off negotiations. Copeland sues for breach; lost profits

***** lower court

      Held that although there are many different interpretations of the letter, the important details of the co-packing agreement "were never agreed to and no reasonable basis upon which to determine them." Thus summary judgment for BR to which Copeland appeals.

**** Questions Presented

     may a party sue for breach of a contract to negotiate an agreement or is such a "contract" merely an unenforcable "agreement to agree"

**** Rule

     contract to negotiate an agreement is distinguishable from a so-called "agreemment to agree" and can be formed and breached just like any other contract. However the only remedy for breach are reliance damages.


**** Reasoning

- why not? people can enter into agreements and there's nothing illegal, so of course they can contract for negotiations
- a contract to negotiate terms is not absurd on its face, it just creates obligations to negotiate; note that this does not, however, it does not create an obligation to agree, only negotiate. This is distinguishable from "an agreement to agree" which does not create any obligations. Previous rulings against this have ruled more on the underlying instrument rather than the obligation to negotiate.

***** arguments against

1. would discourage negotiations by imposing a regime of good faith and fair dealings into every negotiation
2. increase pressure to conclude negotiations for fear they would be held as bad-faith actors
3. precontractual wrong-doing already have remedies in unjust enrichment, promissory fraud and promissory estoppel.
   1. Promissory estoppel is a legal principle that a promise is enforceable by law, even if made without formal consideration, when a promisor has made a promise to a promisee who then relies on that promise to his subsequent detriment.
4. bad faith could cost people millions in expectancy damages when negotiations stall

***** reasons debunking these

1. the contractual imposition of good faith doctrine is due to the intention and request of the parties involved, not negotations in general. this is a contractual obligation which requires both parties to publicly intend to be bound by the promises
2. damages are only reliance damages. while not negotiating huge contracts, jurors understand good faith contract negotiations and can try the facts adequately.
3. the existing remedies are not adequate. unjust enrichment more for ideas or services rendered during negotiations not really for goods and land as here. Promissory fraud is for "a promose made without any intention of performing it" which would not cover the instant case where negotiations were intended but then fell apart. Promissory estoppel works and is basically what is under discussion here.
4. no expectancy charges

***** public policy reasons

      negotiations are complex, take a long time and require the input of many people. "their investmenst in time and money and effort will not be wiped out by the other party's footdragging or change of heart or taking advantage of a vulnerable position created by the negotiation".

***** damages

      reliance is obvious. costly negotiations are relying on the negotiations happening. however, since the outcome is not certain, the terms of the outcome cannot e used for expectancy damages. not talk of restitution damages but negotiations wouldn't seem to have money changing hands outside of the usually returned intial check.


**** Holding

     Disagreement with the method the lower court got there but agreeing in effect. Hold it was valid contract. But Copeland disavowed reliance damages and sought only the lost profit that would have come from the completed instrument. Thus he does not have justicable damages so he cannot sustain his claim and summary judgment is appropriate.

**** Main Takeaway

     contract to negotiate an agreement is distinguishable from a so-called "agreemment to agree" and can be formed and breached just like any other contract. However the only remedy for breach are reliance damages.

* Revoking Offers
  p 295-299

** Dickinson v. Dodds

   In the court of Appeal, 1876

*** Procedural History

**** Facts

     Defendant Dodds give letter of offer to sell property with two days to accept in the post script. Plaintiff Dickinson agrees to accept on the first day but does not notify D believing he has right of refusal until the next day. He learns the land has been sold and sends a notice of acceptance to the man's house and takes efforts to meet him first thing in the morning. He attempts to give him a letter of acceptance before the deadline the next morning and is told that it is too late. He sues for specific performance.

**** Lower Court holding

     Finds there is no grounds to say it is not a contract. The unilateral contract may be concluded by acceptance of the offer and may only be retracted "by the one of th eparties in the meantime, but, in order to be withdrawn from , information of that fact must be conveyed to the mind of the person who is to be affected by it." The fact that the revocation of the offer had not been transmitted by D to P meant that the written acceptance formed a contract binding both, regardless that the land had been surreptitiously sold in the meantime.

*** Questions Presented

    Does knowledge of the sale of a property indicate to a person the retraction of an offer?

*** Rule

    Promises made without consideration create no legal obligation. Contracts must have a "meeting of the minds" whereby both parties agree, at the same time, to be bound.

*** Reasoning

    The promise to hold the offer until a certain date was asserted without consideration from the other side so it has no legal obligation. The idea that retraction must be made official and delivered to the P is without basis. A contract requires a meeting of the minds, so to speak, with an offer continuing in time. It was clear the P knew that the offer had been rescinded in fact so there could be no real offer and thus no meeting of the minds to engage in the sale. "the plaintf knew that Dodds was no longer minded to sell the property to him as plainly and clearly as if Dodds had told him...". The plaintiff knew that the D had changed his mind and was seeking to bind him against a withdrawn offer. It is impossible to say that there was ever "one mind" between the two in the contract.

*** Holding

    There was no meeting of the minds, thus no contract, and therefore no specific performance.

*** Main Takeaway

    Knowedge that the offer is rescinded prevents the meeting of the minds.

* Acceptance
  p 302-309, 323-349

  What is an acceptance? An offer can be revoked until accepted, what is an acceptance?

** The mirror image rule
   Used to determine if there is a contract at all in the absence of partial performance.

   What happens when the acceptance accepts terms different from the offer? one prong is whether there has been any partial performance. without performance, it is easier to contest the existence of mutual assent to contract in finding the acceptance is a counter-offer, in essence, rejecting the original offer. the aim is to ensure that the same thing is offered and accepted.

*** Supreme Court of Minnesota in Langellier v. Shaefer 1887
    "departure from terms invalidates the offer, unless the same is agreed to by the party who made it. Where the negotiations are by letters, they will constitute no agreement unless the answer to the offer is a simple accceptance, without the introduction of any new term."

    Muddy waters after some partial performance. It is clear that the parties intended to contract, the ambiguity is to which terms are they bound? In this case, the mirror image rule is abandoned.

** Ardente v. Horan
   Supreme Court of Rhode Island, 1976
*** Procedural History
**** facts
     Plaintiff made a bid of 250k to D. D agree, have documents drawn up. P send signed documents, $20k check and request to confirm if certain furnishing are included. D refuse to continue the purchase agreement. P sue for specific performance.
**** lower court
     Summary judgment for D. Theory is that the check and documents were not an acceptance but a rejection and a counter offer which D were free to not accept.

*** Questions Presented
    Can an offer be accepted when proposing to include other items in the sale?

*** Rule
    Sorta. If the acceptance is clearly independent of the condition the offer is accepted and understood tht other points can be modified. But the same standard of the public actions of the player are in effect. An acceptance of an offer must be "definite and unequivocal. 'An offeror is entitled to know in clear terms whether the offeree accepts his proposal'."

*** Reasoning

If we are going to obligate people and give them recourse to courts, it must be clear that they are obligated and on what terms they have promised. Had the P only sent the paperwork and check there would be no question; however they also included the letter. As these form the only interaction the D have to judge acceptance, the judgment of a reasonable man will examine only these documents. The language used in the letter was not consistent wth "an absolute acceptance accompanied by a request for a gratuitous benefit". The letter asks for confirmation that the items listed are part of the instant transaction and therefore constitute a negotiation of the primary contract rather than a collateral addition to the main transaction. This removes the certainty and places it in a conditional acceptance which the D are free to reject.

*** Holding

Jugdment of the lower court is affirmed in that no contract was formed due to non-acceptance by the D's of the conditional offer of the P.

** White v Corlies & Tifft
   Court of Appeals of New York (final court in NY)1871
*** Procedural History
**** facts
     A carpenter and merchant negotiate for refurnishing a suite of offices. There is a round of negotiations signed of

**** lower court
     a contract was formed and held for white in his action for breach.

*** Questions Presented
    Does starting performance of a contract serve as a manifestatoin of mutual assent?

*** Rule

    Acceptance does not require that the offering party have knowledge, but that you have sent into motion events that will be unequivocal demonstration of the mutual assent.

*** Reasoning

    White here purchased stock and began working right away but never responded to the letter. While in his mind his actions were clear acceptance of the job, from outside it appeared that he bought some wood and started working it, tasks and materials that resemble his work for any job in general. Absence the manifestation of mutual assent

*** Holding
    The holding was reversed and a new trial ordered.

*** Main Takeaway
    It is not that the knowledge must meet the other party but that events have begun that will demonstrate unequivocably the acceptance.
** Petterson v Pattberg

   Court of Appeals of New York 1928

*** Procedural History

**** facts

     A house has a mortgage on it, owed to Pattberg, the D. He gives Petterson (P) the option of making one more scheduled payment and then paying in full. P makes the scheduled payment and then appears the following month to satisfy the deal in a timely manner. D mentions he cannot accept the money as he has sold the mortgage.

**** lower court

     P brings an action for damages in the amount of $780, the discounted amount for payment in full of the mortgage.

*** Questions Presented

    Was the offer rescinded or was a valid contract breached.

*** Rule

**** Opinion

     "It is elementary that any offer to enter into a unilateral contract may be withdrawn before the act requested to be done has been performed".

**** Dissent

     "if the condition precedent has not been performed, it is because the defendant made performance impossible by refusing th eaccept payment, when the plaintiff came with an offer of immediate performance.

*** Reasoning

**** Ruling of the court

     In this situation, there was no obligation created until the predicate performance was accomplished-- the payment of the debt in full. In light of this, there was only an offer on the table, one necessarily free to withdraw. The court notes that it gets a little strange since until the money is accepted the offer can be withdrawn, but analogize it to someone verbally rescinding an offer before the oferree can mouth the words I accept. As there was a rescinded offer, there cannot be a contract and so there is no issue before the court. In dicta, the author of the opinion takes it further, stating that even if there were tender of the amount before withdrawal, the person would voluntarily have to accept the payment and so would still have a moment of last refusal.

**** Dissent
     There was a simple exchange of promises: pay in full on this date, get a discount. the person shows up to satisfy the condition and then is prevented from doing satisfying the bargin by the person he contracted with to that persons benefit. There is then analysis of what exact act was requested. The gist is that in to pay someone requires their assent; thus if one promises to discount a mortgage if you pay them in full, this case allows them to reject the assent to the payment and then with a clear conscience find you have not satisfied your side of the bargain and decline the conditional offer of the discount.

     "If the defendant intended to induce payment by the plaintiff and yet reserve the right t orefuse payment when offered he should have used a phrase better calculated to express his meaning that the words: 'I agree to accept'. A promise to accept payment, by its very terms, must necessarily become binding, if at all, not later than when a present offer to pay is made".

*** Holding

    The lower courts are reversed and the P was never entitled to damages.

*** Main Takeaway

    Unilateral conditional contracts may be withdrawn up until the point that the conditional clause is satisfied. Strangely, even if the condition's satisfaction requires your assent.

** hobbs v massasoit whip co

   Supreme Judicial Court of MA, 1893

*** Procedural History

**** facts

     a man sent eelskins to a trading company four or five times, they were accepted and paid for. He sent eelskins the last time, never heard a word and the company considered them not accepted.

**** lower court ruling

     Judgment in favor of Hobbs

*** Questions Presented

    Can there be acceptance of a contract with complete silence

*** Rule

    Conduct which gives the appearance of acceptance or assent is considered as such in the eyes of the law.

*** Reasoning

    While true that a stranger cannot mail items and impose a duty on another, this is a far cry from that. There was a standing order for eel skins of a certain quality, which these were. There were previous transactions in good faith. Even if there was no implied acceptance upon receipt of the skins, there was still a duty to act in some way. the silence and not returning of the skins is a way that one could interpret acceptance.

*** Holding

    Hobbs was correct and the lower court is sustained.

** register.com inc v verio, inc

   Us court of appeals, 2nd circuit 2004

*** Procedural History

**** facts
     Register.com is registered with ICANN to issue domain names. Its terms require it to provide whois data along with a disclaimer that the data is not to be used for email marketing. Verio scrapes this for email marketing and direct mail and phone marketing. Verio stops the email usage but points out that technically Register is in violation of its ICANN agreement.

**** previous court

     Defendant Verio appeals from preliminary injunction for Plaintiff.

*** Questions Presented

    Can a oferree deny knowledge of conditions when they arrive with the benefit and can an oferree decline the conditions but still accept the benefits.

*** Rule

    No and no.

*** Reasoning

    While perhaps the first whois query was undertaken without knowning the conditions which attached, subsequent queries were done with this knowledge. Further, the company testified that they were aware. Perhaps this could fly on intermittent or the intial queries but repeated queries throughout the day must be taken to be done with knowledge of the terms. As to the second question, you cannot claim the benefits and disparage the conditions they come under. The defendant was free to not use or free to use and abide but it chose neither. 'silence and inaction operate as an acceptance ... [w]here an offeree takes the benefit of offered services with reasonable opportunity to reject them and reason to konw that they were offered with the expectation of compensation'

*** Holding

    The injunction is correct and may stand

*** dissent

    Just because they knew the terms doesn't mean they assent to them. Vario knows the data is free and public and that ICANN does not put the direct marking and phone call restrictions on the data so they could reasonably reject these terms. Also, Register has no ownership interest in the data; as the terms come with the data and after the database has already been accessed, the user is free to reject the terms and use the data as they see fit.
** Nguyen v barnes and noble
   9th circuit 2014
*** Procedural History

**** facts
     Nguyen attempted to purchase a tablet but stock ran out and he was unable to receive one. sues BN and they remove to Fed court where they argue that controversy is bound by website terms to arbitration under FAA. Website terms are available under terms of use link of every page. He never clicked on terms stating "by visiting any area ... a user is deemed to have accepted the terms of use".

**** previous court ruling
     "B&N did not provide reasonable notice of its terms of use and that nguyen therefore did not unambiguously mainfest assent to the arbitration provision contained therein."

     Just a note, state law dictates whether a contract was formed, and then federal law would dictate whether arbitration is required.

*** Questions Presented
    Can the court infer silent acceptance of the terms of the website.
    "does a website that makes its terms of use available via a conspicuous hyperlink on every page of the website but otherwise provides no notice to users nor prompts them to take any affirmative action to demonstrate assent, even close proximity of the hyperlink to relevan tbuttons user must click on--without--more give rise to constructive notice?" modified to question form. this is presented in the negative in the original.

*** Rule
    In general they can if there is reason to believe that the user is aware of the terms.

*** Reasoning
    Although the internet has changed things, it has not changed the bedrock of contract law, mutual assent. In this case, there is no evidence that the user ever had knowledge of the agreement. "The validity of the browsewrap agreement turns on whether the website puts a reasonably prudent user on inquiry notice of the terms of the contract". B&N put the link next to other functional links that a user would have to use but no case law supports the theory that proximity would put a reasonable prudent user in knowledge of the terms. While there is an unpublished opinion holding that a link to the terms in conspicuous dress can help a user, that case had an enumerated step in the checkout process to review the terms and conditions, a fact distinguishing the instant case.

*** Holding

    With no controlling case law, the court is reluctant to extend the notice element of browsewrap terms notices in creating knowledge in a user. as such, the use of a site does not constitute mutual assent to the terms provided by the site.

*** Main Takeaway
