* liability upon fault

** intro
tort from tortus, twisted, french meaning injury or wrong. is a civil wrong other than a breach of contract. "this area of law imposes duties on persons to act in a manner that will not injure other persons. a person who breaches a tort duty has committed a tort and may be liable to pay damages in a lawsuit brought by a person injured because of that tort."

major purposes
1. provide a peaceful means for adjusting the rights of parties who might otherwise "take the law into their own hands"
2. to deter wrongful conduct
3. to encourage socially responsible behavior
4. to restore injured parties to their original condition, insofar as the law can do this, by compensating them for their injry.

*** notion of tresspass versus case

trespass rooted in criminal law and direct harm. tresspass on the case was a special writ to be applied for on your circumstances; more indirect. the former required no damages as the force and intrusion on the person was enough, accordingly it found no requirement for fault. The latter, being more indirect, required actual damages and attribution or culpability. While tresspass was partly criminal, the case was purely civil to being with; the criminal part of tresspass fell away in the late 1600s. Due to precedence, the actual damages requirement did not fall away with the criminal component but courts were reluctant to extend this standard to the torts descending from tresspass on the case.

** Anonymous

Kings Bench, 1466

*** Rule

"if a man does a thing he isbound to do it in such a manner that by his deed no injury or damage is inflected upon others."

*** Reasoning

There seems to be no case and here the judge is acting apparently as counsel in this case. Seems to be a summary of well settled law at the time.

*** Holding


*** Main Takeaway

** weaver v ward

King's Bench 1616

*** Procedural History

military man against military man, weaver brings suit against ward for trespass of assault and battery. in a training maneuver, gun discharges and wounds the other.

*** Questions Presented



*** Rule

"yet in trespass, which tends only to give damages according to hurt or loss, it is not so; and therefore if a lunatick hurt a man, he shall be answerable in trespass; and therefore no man shall be excused of a tresspass (for this is the nature of an ecuse, and not of a jstification), except it may be judged utterly without his fault."

*** Reasoning

Criminal interaction requires the criminal mind, civil liability requires damages. The court separates things from which you are not liable, a strong standard to reach "as if a man by force take my hand and strike you, or if here the defendant had said, that the plaintiff ran cross his piece when it was discharging" or if the result was "inevitable and that the defendant had committed no negligence to give occasion to the hurt".

*** Holding

Ward was responsible for damages to Weaver

*** Main Takeaway

The standard for liability is "negligence" and based on damages no criminal mind. however, "this is the earliest known case in which it was clearly recognized that a defendant might not be liable, even in a trespass action, for a purely accidental injury occurring entirely without his fault." maybe damages plus? damages plus tie him to it.

** brown v kendall

Supreme Judicial Court of Massachusetts, 1850

*** Procedural History

Two dogs fighting. Defendant, Kendall, in trying to separate them, injuries Brown. In original trial jury is given instructions that the standard of care is in how necessary it was to separate the dogs. For instance, if it were "necessary ... then defendant was required to use only ordinary care in doing it; but if it were only a proper and permissible act, defendant was liable unless he exercised extraordinary care; and that the burden of proving the extraordinary care was on the defendant".

find in favor of plaintiff and defendant appeals.

*** Questions Presented

In an "inadvertant and unintentional [injury]: how far, and under what qualificatoins, the party by whose unconscious act the damage was done is responsible for it".

Does tresspass have some component more than just damages?

*** Rule

"that when the proof is all in, and before the jury, from whatever side it comes, and whether directly proved, or inferred from circumstances, it it appears that the defendant was doing a lawful act, and unintentionally hit and hurt the plaintiff, then unless it also appears to the satisfaction of the jury, that the dfendant is chargeable with some fault, negligence, carelessness, or want or prudence, the plaintiff fails to sustain the burden of proof, and is not entitled to recover.

Overturning "that damage received by a direct act of force from another will be sufficient to maintain an action of trespass, whether the act was lawful or unlawful, and neither wilful, intentional, or careless.

*** Reasoning

Overturning the notion that in injury lay liability. the courts confused the claim of action with what it required. For instance, tresspass was for direct injury and case for indirect; it eventually became conflated that any direct injury _was_ a tresspass and the other had to be proved. This notion is tossed out on its head for an intent based regime.

Flatly tossed out liability from acts of "duty" vs those which are merely "proper and lawful". Not intentional and part of a lawful act; if you want to charge undue care then that is your burden.

*** Holding

Sent back for a new trial to reflect the shifting of proving due care on the defendant to proving undue care on the plaintiff.

*** Main Takeaway

    Intent not fault is the source of liability.
** cohen v petty

court of appeals of the district of columbia, 1933

*** Procedural History

Petty was driving, said he felt sick, fainted and the car ran off the road, permanently injuring plaintiff. Having uncontested testimony that petty said "I feel sick" and then fainted, Trial court directs a verdict, preventing jury consideration.

*** Questions Presented

Can the court find negligence, or even allow for a jury to find negligence, in a man who becomes sick and faints when he had no knowledge of any illness.

*** Rule

no

*** Reasoning

*** Holding

the lower court was correct in not letting this go to jury

*** Main Takeaway

Seriousness of injury, etc, are not the source of liability. it is intent or negligence which must be shown by the evidence.

** spano v perini corp

court of appeals NY 1969

*** Procedural History

Blasting for constructing a tunnel damages cars in nearby or adjacent garage. Sue for damages, winning for plaintiffs (not sure what spano is as this is a combined case). Judgement reveresed on appeal and that affirmed on another appeal landing finally in this case.

*** Questions Presented

*** Rule

Limit to the negligence standard and a glimpse of our ancient tort foundations.

*** Reasoning

Both defendants  allege negligence but neither tries to show in what capacity, relying solely on "absolute liability". its just crazy dangerous. "in such a case, the rule which exonerates a party engaged in a lawful business, when free from negligence, has no application".

*** Holding

Return to a lower court to check the evidence to ensure that the damage is in fact cause by the blasting. "the fact that the magazine was liable to such a contingency, which could not be guarded against or averted by the greatest degree of care and vigilance, evinces its dangerous character... In such a case, the rule which exonerates a party engaged in a lawful business, when free from negligence, has no application".

*** Main Takeaway

The negligence plus standard is not absolute. Absolute liability seems to return back to the ancient roots of torts of sole damage but it makes sense in this case. Categorically has been applied by "[t]he overwhelming majority of American jurisdictoins"

* different types

1. intentional
2. negligence
3. strict liability

* Intentional torts

** intent

*** garrat v dailey

**** Procedural History
Supreme Court of Washington 1955

Ruling in favor of Garrat in past. Focused on lack of intent to cause harm "did not have purpose, intent or design to perform a prank or to effect an assault and battery upon the person of the plaintiff" Garrat appeals

**** Questions Presented

What is intent.

**** Rule

Battery, for these purposes, is the intentional infliction of a harmful bodily contact upon another.

"the act must be done for the purpose of causing the contact or apprehension or with knowledge on the part of the actor that such contact or apprehension was substantially certain to be produced"

**** Reasoning

The opinion says that the facts could support the conclusion but that it would be possible to focus more on them to determine the knowledge of the boy. "While a finding that Brian had no such knowledge can be inferred from the findings made, we believe tht before the plaintiff's action i nsuch a case should be dismissed there should be no question but that the trial court had passed upon that issue;"

**** Holding

The knowledge the boy had at the time should be investigated before the complaint is dismissed.

**** Main Takeaway

Intent is a subjective standard relating to the purpose of the actions or the knowledge the person had.

*** spivey v battaglia

**** Procedural History

**** Questions Presented

**** Rule

**** Reasoning

**** Holding

**** Main Takeaway

*** wagner v state

**** Procedural History

***** facts

standing in line at kmart, grabbed by insane person in custody of the state.

**** Questions Presented

**** Rule

**** Reasoning

**** Holding

**** Main Takeaway

*** ranson v kittner

**** Procedural History

Appellate Court of Illinois, 1889

**** Questions Presented

Is mistake a defense to the mistaken but intentional shooting of a dog while hunting for wolves.

**** Rule

Appellants are clearly liable for the damages caused by their mistake, nowithstanding they were acting in good faith.

**** Reasoning

The law does not require intent to harm but that the act was intentional.

**** Holding

the lower judgment finding liability for the dog was correct.

**** Main Takeaway

Mistake is not a defense to liability. Mistake is not accidental

*** mcguire v almy

**** Procedural History

Supreme Judicial Court of MA, 1937

Can't discern what the lower court held

**** Questions Presented

Can the mentally ill form the intent necessary for intentional torts, here intentional tort of battery.

**** Rule

"in order that an act may be done with the intention of bringing about a harmful or offensive contact ... the act must be done for the pupose of causing the contact or apprehension or with knowledge on the part of the actor that such contact or apprehension is substantially certain t obe produced."

**** Reasoning

There have been criticisms of the united states intent based tort system as the rest of the world seems to have settled on a fault based system. The rule is proven, consistent and does comport with our notions of "essential justice" rather than theorems arising from axioms of civil liability.

**** Holding

The insane are not barred categorically from forming intent for intentional torts. "To be liable, must have been capable of tentertaining that same intent and must have entertained it in fact".

**** Main Takeaway

*** talmage v smith

**** Procedural History

Supreme court of michigan, 1894

Lower court issued instructions that stating that if the defendant threw the stick, not intending to hit anyone, there was no recovery; if he threw the stick, intending to hit someone, but it was a reasonable amount of force there is no recovery; if he threw the stick intending to hit someone and the force used was unreasonable, then it did not matter that he struck someone else. Jury found in favor of plaintiff and defendant appeals.

**** Questions Presented

A man threw a stick at one boy who was on the roof of one of his sheds and hit another boy, causing loss of sight in his eye. Is the man liable for intentional battery. For the purposes of the intentional tort of battery, did Smith intend to hit make contact with talmage?

**** Rule

If in the attempt to commit an intentional tort you commit another tort among the historical trespass causes, the intent to commit the one will satisfy the intent to commit the one actually committed.

**** Reasoning

The right of recovery lie in intentional causing of damages

**** Holding

The defendant committed an intentional battery.

**** Main Takeaway

Among the old actions of trespass, "when the defendant intends any one of the five, and accomplishes any one of the five, the doctrin applies and the defendant is liable, even if the plaintiff was not the intended target". Note that the first jury instruction would appear to be assault and would constitute a battery under the theory of transferred intent.

** battery

*** cole v turner

**** Holding

1. That the least touching of another in anger is a battery
2. If two or more meet in a narrow passage, and without any violence or design of harm, the one touches the other gently it will be on battery.
3. If any of them use violence against the other, to force his way in a rude inordinate manner, it is a battery; or any struggle about the pasage, to that degree as may do hurt, is a battery.

**** Main Takeaway

It sets the stage for the "busy world" theory to be expounded later. That there are incidental touches in the world does not lie a claim; but that incidental touches can rise to such if struggle or violence arise. But that the meat of the tort lie in anger.
*** wallace v rosen

**** Procedural History

**** Questions Presented

**** Rule

**** Reasoning

**** Holding

**** Main Takeaway
