* hypo 1

** text

“No more school, no more books, no more teacher’s dirty looks!” Jackson and Camryn Moore, age 13 and 11, respectively, and brother and sister, shouted this refrain as they got out for summer vacation on Friday, June 15, 2006. The following day, as has been the routine for the past few summers, their parents packed them up and sent them off to rural Wisconsin to spend time with their grandparents, Greg and Lynn (“Lynnie”) Olsen. Even though the farm was not a working farm, some old equipment - a thresher, a tractor, which Greg had sold to his new neighbor Leo Dingle, and a hay bailer - was lying around collecting dust and rusting.

Visiting their grandparents was the highlight of the summer for Jackson and Camryn who loved to fish and swim in the pond, or the “old swimming hole” as it was locally known, on Claus Kringle’s (“Old Man Kringle”) property, which was adjacent to their grandparents’ farm. Sadly, Old Man Kringle died on May 23, 2006. At the funeral, Leo, Old Man Kringle’s nephew, told Greg that he had inherited his uncle’s property and agreed to buy Greg’s tractor. Greg thought Leo was going to use the tractor to turn over the topsoil on his uncle’s property, but Leo wanted to use the tractor to put in a Koi (expensive Japanese fish) pond. Three days later, Leo visited Greg, paid for the tractor, and told him that he would have it picked up in two weeks. During a routine inspection of the property, after leaving Greg and Lynnie’s home that day, Leo discovered the old swimming hole that his uncle had allowed the townsfolk to always use. Having found the swimming hole, Leo decided that he didn’t need to make a new Koi pond, but could turn the old swimming hole into one. So, he pulled out his cell phone and ordered the Koi, which cost $50 - $100 each.

The day of the kids’ arrival, Lynnie made preparations to go into town to pick up her grandchildren from the airport. On her way out the door at two o'clock, Lynnie locked the basement door, believing that Greg was working in the barn, but he was actually asleep in the basement family room. After having picked the kids up, Lynnie stopped at the general store on her way home, which also served as the town post office. When Lynnie arrived at the store, Camryn immediately got out of the car and ran into the store, bumping into Leo, who was saying, to the folks in the store, “I just ordered some Koi and I'm turning the old swimming hole into a Koi pond. So, you know what that means? No Fishing! No Swimming!” Preoccupied with finding the candy aisle, Camryn didn't hear Leo or notice that he had spilled his coffee. Camryn slipped and fell, banging her head on the counter. Through the window, Jackson had spied Mike May, who was commonly known to be the town bully. Jackson decided to stay outside because Mike liked to pick on him and had fought with Jackson in the past. When Jackson saw Camryn fall, he assumed that Mike had pushed his sister down. Jackson ran inside, tackled Mike, and they began to wrestle in the store knocking over a display of drinking glasses near the front door. Mr. Grant, the storeowner, who was in the rear, heard the commotion, and rushed to the front pushing past the other customers. He yelled at the boys to stop fighting, and told them that he was going to call the police.  At that point, he locked the front door.

Grabbing Jackson and Mike by the arm, Mr. Grant eventually pulled the boys apart, and the other customers, most of whom had been shopping at the store for years, and shopped at the store on a regular basis, silently crept to the rear, moved the 70 lb. pickle barrel aside, and left through an old rarely used side door. Lynnie, locked outside, banged on the door and screamed for Mr. Grant to let her in. Mr. Grant stood in front of the door and yelled over his shoulder to Lynnie, “I’m not letting anyone in or out until the police arrive.” Camryn, begging Mr. Grant to let her grandmother in, started to cry as Mr. Grant yelled at her, “No! Not until the police get here!” Fifteen minutes later, Barney Fife showed up and arrested Mike for destruction of property.

Leo, who luckily had retrieved his fish before the excitement, returned to the pond and put in the Koi that afternoon, erecting a sign that read “Koi Pond: No Fishing.” When Jackson and Camryn finally got to their grandparents’ house, they changed into their swim trunks and raced off to the pond, running past Leo’s sign. They jumped on the old tire swing, and landed in the pond. Jackson called out to Camryn, “I bet I can catch one of those fish.” Camryn responded, “I bet you can’t.” Jackson determined to prove his sister wrong, caught one of the Koi but squeezed a little too hard, killing the fish. Jackson threw the dead fish out of the pond, and continued to swim with his sister. An hour or so later, they got out of the pond and headed home. Upon arriving at their grandparents’ house, their grandmother was asleep upstairs and they heard someone banging on the basement door. Much to their surprise, they opened the door to find their grandfather at the top of the basement stairs. The kids let him out, and Lynnie, Greg, Jackson and Camryn all had a good laugh over dinner later that night about their grandfather being locked in the basement. As Jackson and Camryn drifted off to sleep, they could only hope that the rest of their summer break was as exciting as the first day.

** questions

*** What are the causes of action that Jackson can bring and their likelihood of success?

1. False Imprisonment
   1. intent
   2. boundary
   3. physical restraint
   4. no reasonable means of escape
   5. no authority
   6. aware
2. Battery
   1. intentional
   2. harmful or offensive contact
   3. blah blah
   4. defense? defense of property
3. Assault and Battery (shop owner)

*** What are the causes of action that can be brought against Jackson and their likelihood of success?

1. battery
   1. defense: defense of others. two theories: majority jurisdiction: jackson would be able to claim only if the person he was defending could use the same claim. therefore mistake would not be justification. other jurisdictions would look for a reasonable belief
2. assault
3. conversion
4. conversion
5. tresspass to land
   1. defense: customary, implied consent

* hypo 2

** text

A professional insect exterminator dropped a one-gallon jug of extremely toxic pesticide on the street curb in front of Audrey’s house. The jug broke and created a sizeable pool of pesticide on the street. The exterminator left the area without cleaning up the spill. Audrey discovered the spill, read the label on the broken jug, and realized that the spill was a hazard to the environment. Audrey knew that there was no governmental agency in her community that she could call on to clean up the spill. Therefore, she decided to clean it up herself. She did this by soaking up the pesticide with rags. She then put the rags and broken glass in a plastic garbage bag. She planned to take the waste to the city's toxic waste disposal facility in two weeks, which was the next date that the city had scheduled for receipt of toxic waste from citizens.

Audrey knew about spontaneous combustion, and was concerned that the damp rags might combust if kept in a closed plastic bag. She poked holes in the bag to reduce the risk of spontaneous combustion. In addition, she stored the bag in an open barbeque pit in his backyard, rather than in her home. She believed that if a fire did occur, it would do no harm because it would be contained in the barbeque pit.

Ten days later the rags did catch on fire. Sparks from the fire drifted a considerable distance into a neighboring yard owned by Dylan. Dylan’s yard was overgrown by very tall weeds. Because it was dry season, the weeds easily caught fire from the spark. The fire quickly spread and damaged Dylan’s house.

Audrey and Dylan live in a city that has an ordinance requiring that homeowners keep weeds cut to a height of no more than four inches. If Dylan had cut his weeds down to four inches, they would not have caught fire. Dylan refused to cut his weeds because he strongly believes that a natural yard is better for the environment because it provides food and shelter for animals, and because lawn mowing causes pollution.

Dylan sues Audrey seeking damages for harm caused by the fire. Dylan has an expert who will testify that environmental cleanup professionals store rags damp with pesticide in sealed metal containers in order to completely eliminate the risk of spontaneous combustion fires.

** questions

*** How do you think Dylan’s lawsuit will be decided? Fully discuss the reasons for your conclusions.

**** negligence elmenst

1. duty: will she be held to a professional standard of care? no reasonable, not professional
2. breach
3. causation
   1. in fact
   2. proximate
4. damages
