* COMMENT facts

Does It Matter?

Larry Smith was arrested and charged with driving while intoxicated. Driving while intoxicated requires a person to operate a motor vehicle while he or she is intoxicated from either alcohol or drugs.

You are interning with the District Attorney's Office, and your supervisor has asked you to write a memo considering whether Larry was operating the vehicle. Below is a list of facts that were discovered during the investigation of this case. You need to determine which facts matter.

(1) Larry Smith is 36 years old.
(2) Sara Smith is Larry's 13-year-old daughter.
(3) Larry is divorced from Sara's mother.
(4) Sara and her four-year-old brother Ray spend half of their time with their mom and half of their time with their dad.
(5) During the week of June 29-July 5, Sara and Ray stayed with Larry.
(6) On July 4, Larry, Sara, and Ray attended a Fourth of July party at his Larry's brother's home.
(7) At the party, the kids played in the pool and with small fireworks, including snaps, smoke bombs, and sparklers.
(8) The adults watched the kids and played spades.
(9) Throughout the afternoon, Larry had three beers and two shots of tequila.
(10) He also ate throughout the day: ribs, salads, fresh fruit, and cupcakes.
(11) The fireworks ended at 11 p.m.
(12) As Larry, Sara, and Ray were about the leave the party, Larry said to Sara, "Do you want to try to drive home? I've got a killer headache, and if you can touch the pedals, you can do it."
(13) Sara said yes.
(14) Sara got behind the wheel and adjusted the seat.
(15) Larry put Ray in his booster seat in the backseat.
(16) Larry got in the front, passenger-side seat.
(17) Both Larry and Sara put their seatbelts on.
(18) At 11:23 p.m., Louisiana State Trooper Ellen Moss was notified of a single-car accident on Louisiana Highway 811.
(19) The accident was reported by Barry Pellegrin, an ambulance driver who noticed a vehicle in the ditch.
(20) Pelligrin reported the accident, ascertained there were no injuries, and then remained at the scene until the police arrived.
(21) Pelligrin indicated that when he arrived, all three occupants were outside the car. Larry was trying to comfort both Ray and Sara, who were both crying.
(22) Pelligrin did not notice a smell of alcohol on Larry.
(23) Trooper Moss observed a 2012 Ford Focus in the ditch facing away from the highway.
(24) Moss concluded that the vehicle had been southbound before it left the roadway.
(25) When Moss first spoke to Larry, she smelled the slight odor of alcoholic beverages.
(26) According to Moss, Larry's speech was deliberate and his eyes were somewhat bloodshot.
(27) At the scene, Larry admitted to Moss that he had been drinking. He told her that he had consumed "A few beers and a couple shots of Jose Cuervo" throughout the day.
(28) Larry also told Moss that Sara had been driving.
(29) Moss interviewed Sara.
(30) Sara told Moss that she had been driving.
(31) Sara said that she put the key in the ignition and started the car.
(32) The car has a stick shift/manual transmission, so Sara had to manipulate the clutch, the gas pedal, and the brake.
(33) Sara told Moss that her grandfather, who is an amateur race car driver, taught her to drive when she was about 10.
(34) Sara told Moss that she had some trouble switching gears when she first got started.
(35) She said Larry, from the passenger seat, initially put the car in reverse while she pressed in the clutch.
(36) She said Larry also helped her shift from third to fourth gear.
(37) Moss looked into the vehicle, and she noticed that the driver's side car seat was pushed almost all of the way forward.
(38) The passenger side car seat was pushed all of the way back.
(39) Moss estimated that Larry was 5 feet 10 inches tall.
(40) She estimated Sara was no more than 5 feet 2 inches tall.
(41) Sara told Moss that the car went into a ditch because a dog ran out into the road.
(42) Sara said that she tried to swerve around the dog, and she ended up in the ditch.
(43) Moss administered a field sobriety test to Larry.
(44) Larry passed the test.
(45) Larry agreed to a breath test.
(46) The test indicated that Larry's blood alcohol level was 0.09, just over the legal limit.
(47) Larry, Sara, and Ray were placed in the backset of the police cruiser.
(48) They were taken to the police station.
(49) Moss called Sara and Ray's mother to pick them up.
(50) When the mother arrived, she told Moss that even though Sara was young, she was a good driver.
(51) Sara had driven a number of different vehicles on her grandfather's property throughout her life.
(52) With her mom present, Sara answered a few more questions.
(53) Sara said she was driving at 45 miles per hour, the posted speed limit.
(54) Sara admitted that she did not have a driver's license.
(55) Sara also indicated that she had not taken driver's education and she did not have a learner's permit.
(54) When asked why she thought her dad asked her to drive, Sara answered, "Because I had been bugging him all week, and he had a bad headache."
(55) It was also revealed that Larry suffers from debilitating migraines, and he has been advised by his physician not to drive when he has one.

** Brief Summary

   At a family get-together, Larry Smith consumed alcohol. After the fireworks ceased at 11 p.m., the family left. The vehicle was found in a ditch along the roadside with Larry and his two children outside of the vehicle. The family maintains that the daughter, Sara, age 13, was the one driving. According to the recounting of the family, Larry's only involvement with the vehicle's operation was putting the car initially in reverse, and aiding Sara in shifting once from third to fourth gear. Both of these interactions with the controls of the vehicle were from the passenger seat. A breath test administered indicated that Larry's blood alcohol level was 0.09. This case has two avenues for prosecution under LA R.S 14:98 which criminalizes operation of a vehicle while intoxicated: whether the story is a reasonable one or if Larry was the actual driver at the time of the crash, and in the alternative, whether Larry's operation of the vehicle's controls from the passenger seat satisfies the statutory element of operation.

** relevant facts

On July 4, Larry Smith took his two children Sara, and Ray to a Fourth of July party at his Larry's brother's home. Throuhout the afternoon, Larry had three beers and two shots of tequila. The party ended at 11 p.m. As Larry, Sara, and Ray were about the leave the party, Larry said to Sara, "Do you want to try to drive home? I've got a killer headache, and if you can touch the pedals, you can do it." Sara said yes. Sara got behind the wheel and adjusted the seat. At 11:23 p.m., Louisiana State Trooper Ellen Moss was notified of a single-car accident on Louisiana Highway 811. Paramedics arrived before officer Moss and indicated that when he arrived, all three occupants were outside the car. Larry was trying to comfort both Ray and Sara, who were both crying. When Moss first spoke to Larry, she smelled the slight odor of alcoholic beverages. According to Moss, Larry's speech was deliberate and his eyes were somewhat bloodshot. At the scene, Larry admitted to Moss that he had been drinking. He told her that he had consumed "A few beers and a couple shots of Jose Cuervo" throughout the day. Larry also told Moss that Sara had been driving.

Larry also told Moss that Sara had been driving. Moss interviewed Sara. Sara told Moss that she had been driving. Sara said that she put the key in the ignition and started the car. The car has a stick shift/manual transmission, so Sara had to manipulate the clutch, the gas pedal, and the brake. Sara told Moss that her grandfather, who is an amateur race car driver, taught her to drive when she was about 10. Sara told Moss that she had some trouble switching gears when she first got started. She said Larry, from the passenger seat, initially put the car in reverse while she pressed in the clutch. She said Larry also helped her shift from third to fourth gear. Moss looked into the vehicle, and she noticed that the driver's side car seat was pushed almost all of the way forward. The passenger side car seat was pushed all of the way back. Moss estimated that Larry was 5 feet 10 inches tall. She estimated Sara was no more than 5 feet 2 inches tall. Sara told Moss that the car went into a ditch because a dog ran out into the road. Sara said that she tried to swerve around the dog, and she ended up in the ditch.

At the scene, Officer Moss administered a field sobriety test to Larry. Larry passed the test, but agreed to a breath test. The test indicated that Larry's blood alcohol level was 0.09, just over the legal limit. After being taken to the police station, an officer called Sara and Ray's mother to pick them up. When the mother arrived, she told Moss that even though Sara was young, she was a good driver. Sara had driven a number of different vehicles on her grandfather's property throughout her life. When asked why she thought her dad asked her to drive, Sara answered, "Because I had been bugging him all week, and he had a bad headache."

** questions presented

*** COMMENT template

Under insert applicable law here, did insert issue present here, when…give hypo-specific facts here?

*** Question 1

Under LA R.S. 14:98, does the circumstantial evidence exclude the reasonable hypothesis that Sara, Larry's daughter, was the driver of the automobile, such that the circumstantial evidence can sustain a conviction of Larry for operation of the vehicle while intoxicated?

*** Question 2

Under LA R.S. 14:98, does the fact that Larry, from the passenger seat, put the car into reverse intially and that he helped his daughter shift from third to fourth gear qualify as operation of the vehicle?

** Short answer

*** question 1

The evidence does not exclude the reasonable hypothesis that Sara, Larry's daughter, was driving the vehicle at the time of the crash. The seats were set in a manner consistent with this theory. This recounting of events was given at the time of the accident and the mother, talking to officers at the police station without collaborating with Larry, indicated that Sara had been driving for some time, albeit on private property. The evidence from the scene is consistent with this version of events and thus Larry cannot be assumed to be the driver at the time of the crash.

*** question 2

Larry's operation of the gearshift on at least two occassions will satisfy the operation element for the purposes of LA R.S. 14:98, providing for a successful prosecution under that statute. The courts have looked for operation of vehicle controls to satisfy this element, which is certainly present. This situation differs, certainly, as these other occassions have been in a context where that person was the driver of the vehicle, not the passenger. The statute does not require this, however. It also criminalizes a broader category of conduct than merely driving a vehicle while intoxicated, it criminalizes operating a vehicle while intoxicated.
