* State v Byrd

** Procedural History
SC LA 1980

Convicted in lower court of armed robbery, appeals to supreme court because it was a toy gun

** Questions Presented

Does a toy gun qualify as a "dangerous weapon" when brandished during a robbery?

Sent back as toy gun does not qualify but elements of simple robbery were proven. Instructions for sentencing on lesser charge.


** Rule

"wsa not used in robbery in manner likely to produce bodily harm, toy pistol did not constitute a 'dangerous weapon' within contemplation of statute proscribing armed robbery and defining dangerous weapon".

"When evidence does not support conviction of crim charged, discharge of defendant is neither necessary nor proper when evidence supports conviction on lesser and included offense"

sentencing on lesser charge not actually charged "does not constitute interference with the function of trial judge or jury, does ont deprive defendant of his right to have trial judge or jury decide on proof of elements of lesser and included offense, does not subject D to double jeopardy and is not contrary to federal constitutional principle that jury verdict must not stand if, when evidence is viewed in light most favorable to prosecution, rational jury could not have found essential elements of crime beyond reasonable doubt".

"victim's potential reaction to an instrumentality not inherently dangerous can be considered by the jury in determining whether the instrumentality 'in the manner used' is likely to produce great bodily harm and is therefore a 'dangerous weapon'".
** Reasoning

Looking at reaction of the victim and manner of the assailant, the dangerous situation contemplated by he law was not created. Noting the dramatic differences in sentencing aligning with the legislature's intent, the crime did not arise to the level intended for 'truly dangerous intrumentalities'.

** Holding

** Main Takeaway

Clarification of State v. Levi which held that a non-functioning weapon could still be a "dangerous weapon".
